E90={"A":"E90","B":"E90","C":"E90"}
P18={"A":"E180","B":"E180","C":"E90"}
DEZ=[
dict(data="2026-12-01",hora="10:00",janela="Cyber Monday (30/11 a 02/12)",contexto="Cyber Monday",papel="Meio da janela",
 nome="Só os 100 primeiros levam o 4º grátis",publico=E90,
 oferta="Leve 3, pague 2 + os 100 primeiros pedidos com 4 itens levam o 4º grátis (cupom CYBER100, valor revelado no checkout).",
 assunto="Você está entre os 100 primeiros?",assunto_en="Are you among the first 100?",
 pre="Aplique o código no checkout e descubra. Até quarta.",
 hero="Cyber · só para os 100 primeiros · $ % ?",sub="Só os mais rápidos ganham: coloque o cupom CYBER100 e descubra a surpresa no checkout.",
 blocos=["Símbolos \"$ % ?\" em papel rasgado","Cupom CYBER100 + \"só os 100 primeiros\" (limite real no Shopify)","4 produtos","Lembrete: \"Leve 3, pague 2 até quarta\""],
 cta="Descobrir agora",urgencia="Acaba no pedido 100.",
 ref=["turbo"],conexao="Segunda turbo (TURBO100): 1,06 nas 9 lojas e o maior ticket de agosto (US$ 158). Casa com a CM porque a oferta é de carrinho maior.",booster=None),
dict(data="2026-12-02",hora="18:00",janela="Cyber Monday (30/11 a 02/12)",contexto="Cyber Monday",papel="Fechamento da temporada",
 nome="Last call da Cyber",publico=E90,
 oferta="Leve 3, pague 2 + frete grátis, até 23h59.",
 assunto="🚨 [ÚLTIMA CHAMADA] Expira às 23h59",assunto_en="🚨 [FINAL CALL] Expires at 11:59 PM",
 pre="A última oferta da temporada acaba à meia-noite.",
 hero="Última chamada · Cyber · leve 3, pague 2",sub="Expira hoje às 23h59.",
 blocos=["Mecânica e prazo na primeira tela","\"A temporada de ofertas está acabando\"","4 combinações","Linha do tempo 10.10 · 11.11 · Black Week · Cyber com o último em destaque"],
 cta="Montar antes que acabe",urgencia="Meia-noite.",
 ref=["lastcall77"],conexao="Formato de fechamento validado (US$ 105,3 por mil).",
 booster=dict(quando="21h30 (delay de 3h30)",para="nonOpeners",assunto="⏳ A Cyber acaba em 2 horas"),
 canais="SMS/WhatsApp 20h30 para quem clicou e não comprou."),
# ===== 12.12 NATAL ANTECIPADO =====
dict(data="2026-12-07",hora="10:00",janela="12.12 Natal Antecipado",contexto="12.12 Natal Antecipado: o presente garantido antes do Natal",papel="Antecipação 1 de 2: convite com agenda",
 nome="Convite do 12.12",publico=E90,
 oferta="Nenhuma no e-mail. Promete: 12% extra com o cupom 1212 + 24 horas de frete prioritário grátis, com entrega garantida antes do Natal, só no dia 12.",
 assunto="[Nome], seu convite para o Natal Antecipado chegou 🎟️",assunto_en="[Name], your Early Christmas invitation has arrived 🎟️",
 pre="12/12: um dia para resolver os presentes com entrega antes do Natal.",
 hero="12.12 · Natal Antecipado",sub="Um sábado para resolver todos os presentes, com entrega garantida antes do dia 25.",
 blocos=["Horários: 7h e 18h","\"Por que no dia 12\": é o último sábado com entrega garantida em frete padrão para a maior parte do país (conferir com a transportadora)","FAQ: chega antes do Natal? posso trocar depois? tem embrulho? o cupom soma com o preço do site?","Botão \"Confirmar presença\" (tag VIP-1212)"],
 cta="Confirmar presença",urgencia="Só no dia 12.",
 ref=["convite77","wc"],conexao="O frete prioritário grátis por 24 horas foi o 12/12 da marca americana (US$ 9,7 mil de manhã e US$ 14,6 mil no \"Priority Ends at Midnight\" da noite). Todo single day da carteira tem contexto próprio (Summer Sale, End of Summer, New Season Sale). O 12.12 ganha o seu: presente com entrega garantida. Antecipação curta (2 e-mails) porque vem 10 dias depois da Cyber: o dado do VIP Day diz para não empilhar e-mails de promessa.",booster=None),
dict(data="2026-12-09",hora="10:00",janela="Dezembro",contexto="Presentes: os mais pedidos da Black",papel="Catálogo de presentes",
 nome="Presentes que eles vão usar de verdade",publico=E90,
 oferta="Sem cupom. Frete grátis e o selo \"chega antes do Natal\" em cada produto.",
 assunto="[Nome], presentes que eles vão usar de verdade 🎁",assunto_en="[Name], gifts they'll actually use 🎁",
 pre="Os campeões da Black, separados por faixa de preço.",
 hero="Os campeões da Black · separados por faixa de preço",sub="O que mais saiu na Black Week, pronto para presentear.",
 blocos=["Foto grande do número 1 da Black","\"Por preço\": até [valor 1] · até [valor 2] · até [valor 3] · até [valor 4]","\"Os campeões\": 4 produtos","Rodapé: \"Sábado, 12.12, tem Natal Antecipado. Quem confirmou recebe o cupom às 7h.\""],
 cta="Ver os presentes",urgencia="Estoque limitado.",
 ref=["favoritos77","bwcol25","wc"],conexao="Favoritos (1,12, 3,19% de clique) com a navegação por preço de 25/11/2025. O ângulo \"presentes que eles vão usar de verdade\" foi o guia de presentes de maior receita da lista da marca americana (US$ 13,0 mil em 05/12). Faz a ponte para o 12.12.",booster=None),
dict(data="2026-12-11",hora="10:00",janela="12.12 Natal Antecipado",contexto="12.12 Natal Antecipado",papel="Antecipação 2 de 2: véspera com checklist",
 nome="Checklist do Natal Antecipado",publico=E90,
 oferta="Nenhuma nova.",
 assunto="Amanhã é 12.12. Seus presentes estão prontos?",assunto_en="Tomorrow is 12.12. Are your gifts ready?",
 pre="Amanhã às 7h: 12% extra e entrega garantida antes do Natal.",
 hero="Checklist do Natal Antecipado",sub="Amanhã você resolve os presentes em um dia, com entrega antes do dia 25.",
 blocos=["Checklist: faça a lista de quem vai ganhar · confira os endereços de entrega · salve os favoritos · salve o cartão","\"Já com preço de Natal\": 4 produtos","Horários 7h e 18h"],
 cta="Montar minha lista",urgencia="Amanhã às 7h.",
 ref=["check25","vespera88"],conexao="Véspera com checklist, a versão de véspera que vendeu no 8.8 e no 11.11 de 2025.",booster=None,
 canais="SMS/WhatsApp 18h: \"Amanhã é 12.12: 12% extra e entrega antes do Natal.\""),
dict(data="2026-12-12",hora="07:00",janela="12.12 Natal Antecipado",contexto="12.12 Natal Antecipado",papel="Pico: disparo 1",
 nome="Cupom liberado (texto de pessoa)",publico=E90,
 oferta="12% extra com o cupom 1212 + 24 horas de frete prioritário grátis, com entrega garantida antes do Natal, até 23h59.",
 assunto="Seu cupom foi liberado ✅",assunto_en="Your coupon has been released ✅",
 pre="1212: 12% extra e o presente chega antes do Natal.",
 hero="Texto puro, remetente pessoa",sub="",
 blocos=["\"Oi, [nome]. Hoje é Natal Antecipado.\"","\"O cupom **1212** dá 12% extra e o frete é grátis, com entrega garantida antes do dia 25. Só até 23h59.\"","\"Separei os presentes que mais saíram na Black: [link]\"","Assinatura"],
 cta="Link no texto",urgencia="Até 23h59.",
 ref=["cupom99"],conexao="07h em texto, validado (9.9 e Clube Rock).",booster=None,
 canais="SMS/WhatsApp 07h05: \"Natal Antecipado: 12% extra com 1212 e entrega antes do Natal.\""),
dict(data="2026-12-12",hora="18:00",janela="12.12 Natal Antecipado",contexto="12.12 Natal Antecipado",papel="Pico: principal do dia",
 nome="Status mudou (conversa)",publico=P18,
 oferta="12% extra com 1212 + frete prioritário grátis, até 23h59.",
 assunto="🚨 Seu status acaba de mudar",assunto_en="🚨 Your status has just changed",
 pre="Faltam 6 horas para garantir os presentes com 12% extra.",
 hero="Conversa de celular",sub="",
 blocos=["Conversa: \"Resolvi os presentes todos hoje, 12% extra com 1212\" · \"E chega antes do Natal?\" · \"Garantido. Mas o cupom é só hoje\"","Cupom 1212 + selo de entrega","4 produtos","Garantias"],
 cta="Garantir os presentes",urgencia="Até 23h59.",
 ref=["conversa88"],conexao="O 18h de maior índice da carteira.",
 booster=dict(quando="21h30 (delay de 3h30)",para="nonOpeners",assunto="🚨 [ÚLTIMA CHAMADA] O 12.12 expira às 23h59"),
 teste="T7: o 12.12 como single day completo nas lojas BR e global."),
dict(data="2026-12-15",hora="10:00",janela="Dezembro: prazos de Natal",contexto="Prazo de entrega 1 (frete padrão)",papel="Meio de janela com prazo",
 nome="Jornal: últimos dias para chegar antes do Natal",publico=E90,
 oferta="Frete grátis até quinta, 17/12, último dia do frete padrão com entrega antes do Natal.",
 assunto="[Nome], chegou a notícia que você não queria...",assunto_en="[Name], the news you did not want to hear has arrived...",
 pre="O frete padrão com entrega antes do Natal acaba quinta.",
 hero="Breaking news · 48h para o último dia do frete padrão",sub="Pedidos até quinta, 17/12, às 23h59 chegam antes do Natal com frete grátis.",
 blocos=["Cabeçalho de jornal com a data","Caixa com a data de corte da transportadora","Foto da embalagem de presente","\"Os destaques da manchete\": 4 presentes"],
 cta="Escolher o presente",urgencia="48 horas.",
 ref=["jornal22"],conexao="Jornal com prazo de 48 horas, a mesma lógica de 22/07 (1,62 nas 9 lojas). Aqui o prazo é o da transportadora, que é real.",booster=None,
 canais="SMS/WhatsApp 10h05: \"Frete padrão com entrega antes do Natal até quinta.\""),
dict(data="2026-12-17",hora="10:00",janela="Dezembro: prazos de Natal",contexto="Último dia do frete padrão",papel="Fechamento de prazo",
 nome="Notificação do futuro: seu presente chegou a tempo",publico=E90,
 oferta="Último dia do frete grátis padrão com entrega antes do Natal.",
 assunto="[Nome], falta você confirmar esse pedido...",assunto_en="[Name], you still need to confirm your order...",
 pre="Último dia para o presente chegar antes do Natal com frete padrão.",
 hero="Notificação do futuro · Seu presente chegou a tempo ✓",sub="Viemos do dia 24 avisar: você não deixou para a última hora. Hoje é o último dia do frete padrão.",
 blocos=["Fundo branco","Resumo de pedido simulado com a data de entrega \"até 23/12\"","\"Válido até hoje às 23h59\"","4 presentes"],
 cta="Confirmar meu presente",urgencia="Até 23h59.",
 ref=["notif"],conexao="Formato de fechamento da carteira (1,67), com o prazo mais real do ano.",booster=None),
dict(data="2026-12-18",hora="10:00",janela="Dezembro: prazos de Natal",contexto="Esqueceu alguém?",papel="Texto do fundador, última semana",
 nome="Esqueceu alguém? A gente resolve",publico=E90,
 oferta="Frete expresso com entrega antes do Natal até segunda, 21/12, e o vale-presente para quem ficou de fora.",
 assunto="Esqueceu alguém? A gente resolve",assunto_en="Forgot someone? We've got you",
 pre="Ainda chega antes do Natal. E se não chegar, tem o vale-presente.",
 hero="Texto do fundador",sub="",
 blocos=["\"Oi, [nome]. Todo ano tem aquela pessoa que a gente lembra na última semana.\"","\"Se for o seu caso: com frete expresso, pedidos até segunda (21/12) ainda chegam antes do Natal. ESCOLHER O PRESENTE >>>\"","\"E se nem assim der tempo, o vale-presente chega por e-mail em 1 minuto. MANDAR UM VALE-PRESENTE >>>\"","Assinatura"],
 cta="ESCOLHER O PRESENTE >>>",urgencia="Frete expresso até segunda.",
 ref=["reabertura","wc"],conexao="Na lista da marca americana, o texto \"Forgot Someone? We've Got You\" (18/12) foi o e-mail de maior receita de dezembro (US$ 19,0 mil). Aqui ele entra no formato de texto do fundador da nossa reabertura (1,15).",booster=None,evid="validado (formato) + inspiração (ângulo)"),
dict(data="2026-12-19",hora="10:00",janela="Dezembro: prazos de Natal",contexto="Prazo de entrega 2 (frete expresso)",papel="Mesma mensagem, formato novo",
 nome="A transportadora está te ligando",publico=E90,
 oferta="Frete expresso com entrega antes do Natal até segunda, 21/12.",
 assunto="[Nome], você tem uma chamada recebida 📞",assunto_en="[Name], you have an incoming call 📞",
 pre="O expresso ainda chega antes do Natal.",
 hero="Chamada recebida: \"Ainda chega antes do Natal\"",sub="Celular com a chamada, botões recusar e atender.",
 blocos=["Oferta na tela: \"frete expresso · entrega até 24/12 · pedidos até segunda\"","\"Os presentes na linha\": 4 produtos","Rodapé com as datas de corte"],
 cta="Atender",urgencia="Até segunda.",
 ref=["ligacao"],conexao="Ligação: 1,17 na amostra ampla, feita para o último momento de uma oferta.",booster=None,
 canais="SMS/WhatsApp 10h05: \"Frete expresso ainda chega antes do Natal. Até segunda.\""),
dict(data="2026-12-21",hora="10:00",janela="Dezembro: prazos de Natal",contexto="Último dia para chegar antes do Natal",papel="Fechamento",
 nome="Last call de Natal",publico=P18,
 oferta="Último dia do frete expresso com entrega antes do Natal.",
 assunto="🚨 [ÚLTIMA CHAMADA] Último dia para chegar antes do Natal",assunto_en="🚨 [FINAL CALL] Last day for delivery by Christmas",
 pre="Pedidos até 23h59 de hoje chegam antes do dia 25.",
 hero="Última chamada · o presente ainda chega",sub="Pedidos até 23h59 de hoje chegam antes do dia 25.",
 blocos=["Prazo na primeira tela","\"Depois de hoje, só o vale-presente chega a tempo\"","4 presentes","Linha do tempo 15 · 17 · 19 · 21 com o último em destaque"],
 cta="Garantir o presente",urgencia="Meia-noite.",
 ref=["lastcall77"],conexao="Formato de fechamento validado (US$ 105,3 por mil).",
 booster=dict(quando="18h (delay de 8h)",para="nonOpeners",assunto="⏳ O último prazo para o Natal acaba hoje")),
dict(data="2026-12-22",hora="10:00",janela="Dezembro: prazos de Natal",contexto="O presente que chega em 1 minuto",papel="Última hora",
 nome="Presente de última hora, resolvido",publico=E90,
 oferta="Vale-presente digital, entregue por e-mail na hora. Valores: [valores].",
 assunto="Presente de última hora, resolvido",assunto_en="Last-minute gifting, solved",
 pre="O vale-presente chega em 1 minuto por e-mail.",
 hero="Texto puro, remetente pessoa",sub="",
 blocos=["\"Oi, [nome]. Se o presente não chega mais a tempo, o vale-presente chega em 1 minuto.\"","\"Você escolhe o valor, a pessoa recebe por e-mail e escolhe o que quiser.\" [link]","Assinatura"],
 cta="Link no texto",urgencia="Até a noite do dia 24.",
 ref=["reabertura","wc"],conexao="Texto do fundador, formato validado da carteira. O ângulo \"Last-Minute Gifting, Solved\" (22/12) foi o segundo e-mail de maior receita de dezembro da marca americana (US$ 18,2 mil). O vale-presente é o único produto que não depende de transportadora.",booster=None,
 canais="Push 24/12 09h: \"Vale-presente até o meio-dia\"."),
dict(data="2026-12-26",hora="07:00",janela="Boxing Day (trilha UK e EU)",contexto="Boxing Day",papel="Pico: disparo 1",
 nome="Boxing Day starts now",publico=E90,
 oferta="Boxing Day: [oferta da loja] com o cupom BOXING, até 23h59.",
 assunto="Your Boxing Day coupon has been released ✅",assunto_en="Your Boxing Day coupon has been released ✅",
 pre="Boxing Day deals are live until 11:59 PM.",
 hero="Texto puro, remetente pessoa (inglês)",sub="",
 blocos=["\"Hi [Name], our Boxing Day sale is live.\"","\"Use **BOXING** for [offer], until 11:59 PM tonight.\" [link]","Assinatura"],
 cta="Link no texto",urgencia="Tonight.",
 ref=["cupom99"],conexao="Só lojas UK e EU. Estrutura de 07h validada.",booster=None,trilha="uk_eu"),
dict(data="2026-12-26",hora="18:00",janela="Boxing Day (trilha UK e EU)",contexto="Boxing Day",papel="Pico: principal do dia",
 nome="Status changed (conversa)",publico=P18,
 oferta="Boxing Day com BOXING, até 23h59.",
 assunto="🚨 Your status has just changed",assunto_en="🚨 Your status has just changed",
 pre="Final hours of Boxing Day.",
 hero="Conversa de celular (inglês)",sub="",
 blocos=["Conversa sobre o Boxing Day","Cupom BOXING","4 produtos","Garantias"],
 cta="Shop now",urgencia="11:59 PM.",
 ref=["conversa88"],conexao="O 18h de maior índice da carteira.",booster=None,trilha="uk_eu"),
dict(data="2026-12-28",hora="10:00",janela="Fim de ano",contexto="Reabertura de fim de ano",papel="Reabertura",
 nome="Eu decidi reabrir os preços da Black por 3 dias",publico={"A":"E90","B":"E90","C":"E30"},
 oferta="Preços da Black Week de volta nos itens que sobraram, até 30/12 às 23h59.",
 assunto="Eu decidi reabrir os preços da Black por 3 dias",assunto_en="I decided to reopen Black Friday prices for 3 days",
 pre="Só no que sobrou do estoque. Até quarta.",
 hero="Texto de pessoa",sub="",
 blocos=["\"Oi, [nome]. Sobrou estoque de alguns produtos da Black, e eu prefiro que eles saiam com você do que fiquem para o ano que vem.\"","\"Voltei os preços da Black Week nesses itens, até quarta, 30/12, às 23h59.\" [link]","Assinatura"],
 cta="Link no texto",urgencia="Até quarta.",
 ref=["reabertura"],conexao="Reabertura: 1,15 na amostra ampla. No fim de ano, o motivo é real (estoque) e não ensina a lista a esperar, porque a próxima Black é só em 2027.",booster=None),
dict(data="2026-12-30",hora="10:00",janela="Fim de ano",contexto="2026 termina amanhã",papel="Fechamento do ano",
 nome="Ignore este e-mail depois de 31/12",publico=E90,
 oferta="Sem cupom novo. Os preços que estão no site valem até 31/12 às 23h59.",
 assunto="Ignore este e-mail depois das 23h59 de 31/12",assunto_en="Ignore this email after 11:59 PM on Dec 31",
 pre="Até lá, os preços de 2026 continuam valendo.",
 hero="2026 termina amanhã",sub="Os preços que ficaram no ar em dezembro acabam à meia-noite de 31/12. Sem cupom.",
 blocos=["Hero com a data","\"2026, sim. 2027, não.\": 4 produtos","Rodapé de agradecimento e o que vem em janeiro"],
 cta="Aproveitar enquanto dá",urgencia="Até 31/12 às 23h59.",
 ref=["catalogo"],conexao="Catálogo fecha mês (2,91% de clique, 1,13 nas 9 lojas), fechando o ano.",booster=None),
]
