E90={"A":"E90","B":"E90","C":"E90"}
P18={"A":"E180","B":"E180","C":"E90"}
VIPB={"A":"VIP-BLACK","B":"VIP-BLACK","C":"VIP-BLACK"}
BFD={"A":"E180","B":"E90","C":"E90"}
NOV=[
# ===== 11.11 ESQUENTA BLACK FRIDAY =====
dict(data="2026-11-02",hora="10:00",janela="11.11 Esquenta Black Friday",contexto="Esquenta Black Friday: a Black começa no dia 11, e só por convite",papel="Antecipação 1 de 5: carta do fundador",
 nome="Por que a nossa Black começa no dia 11",publico=E90,
 oferta="Nenhuma. Pede o convite: o botão grava a tag CONVITE-1111. Lista VIP-BLACK já está convidada.",
 assunto="Por que a nossa Black começa no dia 11",assunto_en="Why our Black Friday starts on the 11th",
 pre="Uma decisão que eu tomei este ano, e o que ela muda para você.",
 hero="Texto do fundador",sub="",
 blocos=["\"Oi, [nome]. Aqui é o [Nome], fundador da [Loja], falando direto com você.\"",
  "\"Todo ano é a mesma coisa: a Black chega, o site fica lotado, o frete atrasa e os produtos que mais saem acabam no primeiro dia. Este ano eu decidi fazer diferente.\"",
  "\"A nossa Black vai começar no dia 11 de novembro, duas semanas antes, só para quem tiver convite. Por 24 horas, os 24 produtos que mais vendem com até 50% e mais 22% extra.\"",
  "\"Os convites são limitados porque o estoque é limitado. Se você quer um, é só clicar aqui: QUERO MEU CONVITE >>>\"",
  "\"Quem já está na lista VIP da Black não precisa fazer nada. O convite chega na quarta.\" Assinatura."],
 cta="QUERO MEU CONVITE >>>",urgencia="Convites limitados ao estoque.",
 ref=["reabertura","wc"],conexao="O aquecimento de 2025 planejava abrir com o e-mail do CEO criando a lista selecionada, e na lista da marca americana o texto do fundador explicando o acesso antecipado (\"Why We're Doing EA\") teve 59% de abertura e US$ 11,8 mil. O formato é o da nossa reabertura de 25/07 (texto do fundador, 1,15). O convite por pedido é a lógica das \"ofertas só por convite\" da Amazon: a pessoa pede, e isso já é compromisso.",
 booster=None,evid="validado (formato) + inspiração (ângulo)"),
dict(data="2026-11-04",hora="10:00",janela="11.11 Esquenta Black Friday",contexto="Esquenta Black Friday",papel="Antecipação 2 de 5: convite + oferta do dia do esquenta",
 nome="Seu convite chegou + a oferta do dia do esquenta",publico={"A":"CONVITE-1111 + VIP-BLACK + E90","B":"CONVITE-1111 + VIP-BLACK + E90","C":"CONVITE-1111 + VIP-BLACK + E90"},
 oferta="Convite para o dia 11 (até 50% + 22% extra, 24 produtos, 24 horas). No e-mail: 1 produto com preço de Black por 24 horas (oferta do dia do esquenta).",
 assunto="[Nome], seu convite para a Black Antecipada chegou 🎟️",assunto_en="[Name], your Black Friday Early Access invitation has arrived 🎟️",
 pre="11/11, 24 horas, 24 produtos. E hoje tem uma oferta do dia.",
 hero="Esquenta Black Friday · Você está convidado para o dia 11",sub="Dia 11 de novembro, 24 horas, os 24 produtos que mais vendem com até 50% e mais 22% extra. Quem tem convite entra às 00h01.",
 blocos=["Topo: \"Seu convite: ativo\" (quem tem VIP-BLACK ou CONVITE-1111) ou \"Ainda dá para pedir o seu\" (demais)",
  "\"OFERTA DO DIA DO ESQUENTA\": 1 produto com preço de Black, só até 23h59 de hoje, com a barra \"[X]% já vendido\" (real)",
  "\"Por que não dá para perder o dia 11\": ✓ até 50% + 22% extra · ✓ os 24 mais vendidos · ✓ frete prioritário · ✓ uma vez por ano",
  "\"Como garantir\": 1. de 04 a 10/11 escolha e deixe no carrinho · 2. no dia 10, alarme às 23h55 · 3. às 00h01 finalize",
  "Contagem \"Faltam 7 dias\""],
 cta="Ver a oferta do dia",urgencia="A oferta do dia acaba às 23h59. A lista de convites fecha no dia 10.",
 ref=["anuncio25","convite77"],conexao="O convite é a antecipação de maior índice de 2026, e o anúncio de 05/11/2025 já trazia a lista VIP e os 3 passos. A novidade é a oferta do dia do esquenta, a lógica do Esquenta Black Friday do Mercado Livre (uma oferta por dia com a barra de vendido), que resolve o que a carteira já viu: a antecipação vende quando tem produto em oferta no site (8.8 e 9.9).",
 booster=None,evid="validado + inspiração (Mercado Livre)"),
dict(data="2026-11-06",hora="10:00",janela="11.11 Esquenta Black Friday",contexto="Esquenta Black Friday",papel="Antecipação 3 de 5: prova, carrinho pronto e oferta do dia",
 nome="Os 6 que sempre esgotam + monte seu carrinho",publico=E90,
 oferta="Nenhum cupom novo. Oferta do dia do esquenta nº 2 (1 produto, 24 horas).",
 assunto="[Nome], você já viu o que está vindo? 👀",assunto_en="[Name], have you seen what is coming? 👀",
 pre="Acabamos de conferir o estoque da Black. Estes 6 acabam primeiro.",
 hero="Os 6 produtos que sempre esgotam",sub="Acabamos de conferir o estoque da Black Antecipada. Estes são os 6 que acabaram primeiro nas últimas datas.",
 blocos=["Grade 2x3 com os 6 (dado real: esgotaram no 10.10 ou no 9.9), com \"disponível dia 11\"",
  "\"Por que estou te mostrando isso?\" \"Para você chegar às 00h01 sabendo o que quer.\"",
  "\"Faça isso agora\": entre em cada produto · coloque no carrinho · no dia 11 é só aplicar o cupom",
  "\"OFERTA DO DIA DO ESQUENTA nº 2\" com a barra de vendido",
  "Agenda do dia 11: 00h01 convidados · 7h cupom para todos · 11h clube VIP · 18h última atualização"],
 cta="Montar meu carrinho",urgencia="Faltam 5 dias.",
 ref=["prova25","agenda77"],conexao="Junta a tangibilização de 07/11/2025 (os 6 que sempre esgotam) com a agenda do 7.7 (maior abertura de 2026, assunto com receita 1,77). A tarefa de montar o carrinho é o passo 1 de 2025 e o \"hoje é o dia de escolher, amanhã é o dia de fechar\" do 9.9.",
 booster=None),
dict(data="2026-11-08",hora="10:00",janela="11.11 Esquenta Black Friday",contexto="Esquenta Black Friday",papel="Antecipação 4 de 5: acesso confirmado e bônus / última chance do convite",
 nome="Acesso confirmado + bônus progressivo / Última chance de pedir o convite",publico={"A":"Convidados (VIP-BLACK + CONVITE-1111) · demais E90","B":"Convidados · demais E90","C":"Convidados · demais E90"},
 oferta="Convidados: bônus progressivo para os 100 primeiros pedidos com 2 ou mais itens (10%, 15%, 20% extra sobre o carrinho). Demais: último dia para pedir o convite.",
 assunto="Convidados: [Nome], seu acesso está confirmado ✅ · Demais: Última chance: os convites fecham em 48h",assunto_en="[Name], your access is confirmed ✅ / Last chance: invitations close in 48h",
 pre="Convidados: 00h01 e um bônus só para os 100 primeiros. Demais: depois de terça, só a fila comum.",
 hero="Convidados: \"Acesso confirmado: 00h01 do dia 11\" · Demais: \"Os convites fecham em 48 horas\"",sub="",
 blocos=["Convidados: passe com data, hora 00h01, cupom exclusivo por e-mail e frete prioritário",
  "Convidados: \"BÔNUS REVELADO\": 10% · 15% · 20% para os 100 primeiros (caixas grandes com os números)",
  "Demais: \"Quem tem convite: entra à meia-noite · estoque cheio · bônus dos 100\" contra \"Quem não tem: entra às 7h · o que sobrar · sem bônus\"",
  "Demais: \"Como pedir o seu\" em 2 passos + botão \"QUERO MEU CONVITE\"",
  "Os dois: oferta do dia do esquenta nº 3"],
 cta="Convidados: \"Montar meu carrinho\" · Demais: \"Quero meu convite\"",urgencia="Convites até terça às 23h59.",
 ref=["bonus25","lastvip25"],conexao="Assunto de acesso confirmado (receita 1,48, 3 de 3) com o bônus progressivo dos 100 primeiros de 08/11/2025. Para quem não pediu, o \"VIP list ends today\" de 23/11/2025 transforma a antecipação em prazo.",
 booster=None),
dict(data="2026-11-10",hora="10:00",janela="11.11 Esquenta Black Friday",contexto="Esquenta Black Friday",papel="Antecipação 5 de 5: véspera com checklist",
 nome="Checklist do 11.11",publico=E90,
 oferta="Nenhuma nova. Última oferta do dia do esquenta.",
 assunto="Amanhã é 11.11. Você está pronto?",assunto_en="Tomorrow is 11.11. Are you ready?",
 pre="24 horas de ofertas que não voltam. Convidados entram à meia-noite.",
 hero="24 horas de ofertas que não se repetem",sub="Amanhã, a partir da 00h01 (convidados) ou das 7h (todos). Hoje é o dia de escolher. Amanhã é o dia de fechar.",
 blocos=["Horários: 00h01 · 7h · 11h · 18h","\"Os favoritos que esgotam rápido no 11.11\": 2 produtos grandes","\"Checklist 11.11\": ⏰ alarme 23h55 · 📦 confirme o endereço · 🛒 carrinho montado · 💳 cartão salvo no site","\"Te vejo à meia-noite\" + \"[N real] pessoas já pediram o convite\""],
 cta="Conferir meu carrinho",urgencia="Amanhã, das 00h01 às 23h59.",
 ref=["check25","esq99b"],conexao="Véspera de 10/11/2025 com o checklist, o formato de véspera que vendeu em 2026 (8.8: 10 pedidos), e a frase do 9.9 \"hoje é o dia de escolher, amanhã é o dia de fechar\".",
 booster=None,canais="SMS/WhatsApp 18h: \"Amanhã é 11.11. Convidados entram 00h01, todos às 7h.\""),
dict(data="2026-11-11",hora="00:01",janela="11.11 Esquenta Black Friday",contexto="11.11 Black Antecipada",papel="Pico: acesso antecipado VIP",
 nome="Black Friday Early Access",publico={"A":"Convidados (VIP-BLACK + CONVITE-1111)","B":"Convidados (VIP-BLACK + CONVITE-1111)","C":"Convidados (VIP-BLACK + CONVITE-1111)"},
 oferta="Até 50% no site + 22% extra com o cupom BLACKVIP, só para os convidados, até 23h59. Frete prioritário.",
 assunto="🔓 Sua Black começou antes",assunto_en="🔓 Your Black Friday started early",
 pre="00h01: a lista VIP entra agora. O público só às 7h.",
 hero="Black Friday Early Access · até 50% OFF + 22% extra",sub="11/11 · só até 23h59 · cupom BLACKVIP",
 blocos=["Caixa de destaque: \"24 horas · 24 produtos · 22% extra\"",
  "\"O grande dia chegou\": \"Separamos os 24 mais vendidos da loja. Colocando no carrinho com o cupom, entra o 22% extra. Esta oferta é só do 11.11 e não se repete este ano.\"",
  "\"É simples\": escolha · carrinho · cupom BLACKVIP · pronto",
  "Grade dos 24 (ou os 4 primeiros com \"ver os 24\")",
  "\"Por que não deixar para depois\": os 24 esgotam · 50% + 22% · recebe antes · frete prioritário · exclusivo do dia"],
 cta="Usar o cupom agora",urgencia="Até 23h59 de hoje.",
 ref=["early25"],conexao="É o primeiro disparo do 11.11 de 2025, agora às 00h01 e só para a lista VIP (o passo 2 de 2025 já pedia o alarme para 00:01). Oferta dupla na primeira tela, o formato da semana que mais vendeu em 2026.",
 booster=None,teste="Só dispara se o T1 do 10.10 mostrar venda nova (e não só antecipada)."),
dict(data="2026-11-11",hora="07:00",janela="11.11 Esquenta Black Friday",contexto="11.11 Black Antecipada",papel="Pico: disparo 1 (público)",
 nome="Cupom liberado (texto de pessoa)",publico=E90,
 oferta="Até 50% + 22% extra com o cupom 1111, até 23h59.",
 assunto="Seu cupom foi liberado ✅",assunto_en="Your coupon has been released ✅",
 pre="1111: 22% extra nos preços da Black Antecipada. Só hoje.",
 hero="Texto puro, remetente pessoa",sub="",
 blocos=["\"Oi, [nome]. A Black começou antes, e só por hoje.\"",
  "\"O cupom **1111** dá 22% extra em cima de preços até 50% menores. Vale até 23h59.\"",
  "\"Separei os 24 que mais vendem: [link]. Os 6 primeiros costumam acabar antes do almoço.\"",
  "Assinatura + \"P.S. A Black Week é só dia 25. Este preço não volta até lá.\""],
 cta="Link no texto",urgencia="Até 23h59.",
 ref=["cupom99"],conexao="Versão do 07h do 9.9 (1,66 nas 9 lojas) e da Clube Rock (07h: 1,78, o maior índice da loja). Texto de pessoa, cupom em negrito, um link.",
 booster=None,canais="SMS/WhatsApp 07h05: \"Black Antecipada no ar: 22% extra com 1111 até 23h59. [link]\""),
dict(data="2026-11-11",hora="11:00",janela="11.11 Esquenta Black Friday",contexto="11.11 Black Antecipada",papel="Pico: disparo 2",
 nome="Clube VIP (resgate pendente)",publico=E90,
 oferta="Cupom 1111 na primeira tela + bônus progressivo dos 100 primeiros (contador real).",
 assunto="⚠️ (1) resgate pendente no seu nome",assunto_en="⚠️ (1) pending reward in your name",
 pre="Seu 22% extra ainda não foi usado. Vale até 23h59.",
 hero="11h · Seu 22% extra ainda está aqui",sub="Linha do tempo com 00h01, 7h e 11h marcados. Cupom 1111 na primeira tela.",
 blocos=["Linha do tempo do dia com as marcas",
  "Cupom 1111 + \"até 50% + 22% extra\" em destaque",
  "\"A verdade sobre o clube VIP\": 3 números reais da loja (clientes ativos, compras no ano, quantos receberam este acesso)",
  "\"Os mais vendidos até agora\": 4 produtos + contador do bônus dos 100 primeiros"],
 cta="Resgatar agora",urgencia="O bônus acaba no pedido 100.",
 ref=["relogio99","vip25"],conexao="Estrutura do 11h do 9.9 (relógio e cupom no topo, 1,24 nas 9 lojas) com o bloco do Clube VIP de 2025. Assunto de pendência com contador (6.6 às 11h). A oferta fica na primeira tela.",
 booster=None),
dict(data="2026-11-11",hora="18:00",janela="11.11 Esquenta Black Friday",contexto="11.11 Black Antecipada",papel="Pico: disparo 3 (principal do dia)",
 nome="Status mudou (conversa)",publico={"A":"LT (1 de 2 no trimestre)","B":"E180","C":"E90"},
 oferta="Até 50% + 22% extra com o cupom 1111, até 23h59.",
 assunto="🚨 Seu status acaba de mudar",assunto_en="🚨 Your status has just changed",
 pre="Faltam 6 horas. Abra e veja o que eu separei.",
 hero="Conversa de celular no topo",sub="",
 blocos=["Conversa: A: \"Entrou a Black antecipada, 22% extra com 1111\" · B: \"Já pedi. Dois dos que eu queria esgotaram de manhã\" · A: \"Ainda tem?\" · B: \"Tem, mas acaba meia-noite e não volta até a Black\" · A: \"Indo agora!\"",
  "Foto do produto em uso + cupom 1111",
  "\"Ainda dá tempo de pegar estes\": 4 produtos",
  "\"Agora ou nunca\": cupom repetido + 3 garantias"],
 cta="Aproveitar agora",urgencia="Termina às 23h59.",
 ref=["conversa88"],conexao="O melhor e-mail de 2026 (1,48 na amostra ampla; assunto com receita 2,13) no maior pico antes da Black. Nível A usa a lista toda aqui, no disparo de maior índice.",
 booster=dict(quando="21h30 (delay de 3h30)",para="nonOpeners",assunto="🚨 [ÚLTIMA CHAMADA] A Black Antecipada expira às 23h59"),
 canais="SMS/WhatsApp 20h30 para quem clicou e não comprou: \"Últimas horas da Black Antecipada.\""),
dict(data="2026-11-13",hora="10:00",janela="11.11 Esquenta Black Friday",contexto="11.11: o que sobrou",papel="Pós: aviso de estoque",
 nome="Lamentamos informar",publico={"A":"E90","B":"E90","C":"E30"},
 oferta="Sem cupom. Preço do 11.11 mantido só no que sobrou.",
 assunto="Lamentamos informar que...",assunto_en="We regret to inform you that...",
 pre="Estoque baixo depois do 11.11, preço ainda promocional.",
 hero="Faixa \"Ofertas ativas, sem cupom\" + caixa \"Aviso: 13 de novembro de 2026\"",sub="",
 blocos=["\"Por causa da procura na Black Antecipada, vários produtos estão com estoque bem abaixo do normal. O preço continua, mas quando acabar, não conseguimos repor até a Black Week.\"",
  "\"Ver o estoque que sobrou\"",
  "\"Os últimos\": 4 produtos com unidades reais"],
 cta="Ver o que sobrou",urgencia="Até acabar.",
 ref=["ressaca99"],conexao="Aviso de sistema em fundo branco: a melhor campanha de setembro (14 pedidos). Só engajados.",booster=None),
dict(data="2026-11-16",hora="10:00",janela="Intervalo",contexto="Os favoritos do 11.11",papel="Pós: vitrine dos mais vendidos",
 nome="Os favoritos do 11.11",publico=E90,
 oferta="Sem cupom novo. Frete grátis até quarta, 18/11. Nada de desconto novo antes da Black Week.",
 assunto="[Nome], os favoritos do 11.11 estão te esperando",assunto_en="[Name], your 11.11 favorites are waiting for you",
 pre="Só enquanto durar o estoque.",
 hero="Os mais vendidos do 11.11 · últimas unidades",sub="As peças que todo mundo quis na Black Antecipada ainda estão aqui. Não por muito tempo.",
 blocos=["Foto grande do número 1 do 11.11","\"Os campeões do 11.11\": 4 produtos","Faixa \"Frete grátis até quarta\"","Rodapé: \"Dia 25 começa a Black Week. Amanhã você recebe a agenda.\""],
 cta="Ver os favoritos",urgencia="Estoque limitado.",
 ref=["favoritos77"],conexao="Favoritos do 7.7, oito dias depois: 14 pedidos, 3,19% de clique, 1,12 na amostra ampla. É o pós que funciona melhor que a ressaca.",booster=None),
# ===== BLACK WEEK: antecipacao =====
dict(data="2026-11-18",hora="10:00",janela="Black Week (25 a 29/11)",contexto="Black Week: 5 dias, uma oferta nova por dia",papel="Antecipação 1 de 4: convite com a agenda dos 5 dias",
 nome="Convite da Black Week",publico={"A":"E90 + compradores do 11.11","B":"E90 + compradores do 11.11","C":"E90 + compradores do 11.11"},
 oferta="Nenhuma no e-mail. Anuncia a oferta de cada dia de 25 a 29/11.",
 assunto="[Nome], seu convite para a Black Week chegou 🎟️",assunto_en="[Name], your Black Week invitation has arrived 🎟️",
 pre="5 dias, uma oferta nova por dia. Compradores do 11.11 já estão na lista.",
 hero="Black Week · 25 a 29/11 · 5 dias de ofertas",sub="Esqueça tudo o que você sabe sobre Black Friday. Este ano não é um dia. São 5 dias, e cada um tem uma oferta que não se repete.",
 blocos=["\"Como funciona\": qua 25 · 24 horas, 24 produtos · qui 26 · por coleção e por preço · sex 27 · Black Friday · sáb 28 · monte seu kit · dom 29 · última chamada",
  "\"Bônus: frete expresso para os 50 primeiros de cada dia\"",
  "\"Você está na lista VIP\" (compradores do 11.11 e VIP-BLACK) ou botão \"Garantir meu acesso VIP\"",
  "\"Guarde este número: [N]\" (gancho para o e-mail de 20/11)"],
 cta="Garantir meu acesso VIP",urgencia="A lista VIP fecha dia 24 às 23h59.",
 ref=["bwconvite25","convite77"],conexao="O anúncio da Black Week de 2025 (5 dias, agenda por dia, bônus de frete) no formato de convite, a antecipação de maior índice de 2026.",booster=None),
dict(data="2026-11-20",hora="10:00",janela="Black Week (25 a 29/11)",contexto="Black Week",papel="Antecipação 2 de 4: prova e tarefa",
 nome="O número que você precisa lembrar",publico=E90,
 oferta="Nenhuma. Pede uma ação: salvar os favoritos.",
 assunto="O número que você precisa lembrar: [N] 👀",assunto_en="The number you need to remember: [N] 👀",
 pre="No ano passado, [N] pessoas viram \"esgotado\". Este ano, faça isso antes.",
 hero="[N]: o número da frustração",sub="Na última Black, [N] pessoas clicaram em \"adicionar ao carrinho\" e viram \"esgotado\". (Número real da loja.)",
 blocos=["\"Não seja um deles\" + \"Como chegamos a estes 6 produtos\" (dado de 3 datas)",
  "\"Os 6 que sempre esgotam\": grade 2x3",
  "\"Faça isso agora\": entre em cada produto · clique no coração · pronto, no dia 25 você acha em 2 segundos",
  "\"Confira seu pagamento\": login · cartão · endereço · compra de teste"],
 cta="Salvar meus favoritos",urgencia="Faltam 5 dias.",
 ref=["n1247","agenda77"],conexao="O e-mail de prova e tarefa de 19/11/2025, com a regra do estudo: o número tem de ser o real da loja. O assunto com número segue o padrão \"(1)\" que imita contador.",booster=None),
dict(data="2026-11-22",hora="10:00",janela="Black Week (25 a 29/11)",contexto="Black Week",papel="Antecipação 3 de 4: acesso confirmado / última chance da lista",
 nome="Acesso confirmado (VIP) e última chance (demais)",publico={"A":"VIP + E90 (duas versões)","B":"VIP + E90 (duas versões)","C":"VIP + E90 (duas versões)"},
 oferta="VIP: entra à 00h de quarta com frete expresso grátis no dia 25. Demais: a lista fecha dia 24 às 23h59.",
 assunto="[Nome], seu acesso à Black Week está confirmado ✅ / Última chance: a lista VIP fecha em 48h",assunto_en="[Name], your Black Week access is confirmed ✅ / Last chance: the VIP list closes in 48h",
 pre="VIP: sua entrada é à 00h de quarta. Demais: depois de terça, só na fila comum.",
 hero="VIP: \"Acesso confirmado: 00h de quarta\" · Demais: \"Última chance: a lista VIP fecha em 48h\"",sub="",
 blocos=["VIP: passe com data, hora, frete expresso grátis no dia 25 e o lembrete da agenda dos 5 dias",
  "Demais: \"Quem está na lista ganha: acesso antecipado · desconto exclusivo · produtos liberados antes\" contra \"Quem não entrar até terça: fila comum · o que sobrar · sem o extra\"",
  "Demais: \"Como garantir sua vaga\" em 2 passos + botão",
  "Os dois: \"Lançamento exclusivo para VIPs\" com 4 coleções"],
 cta="VIP: \"Montar meu carrinho\" · Demais: \"Entrar na lista VIP\"",urgencia="A lista fecha terça às 23h59.",
 ref=["lastvip25","bonus25"],conexao="Assunto de acesso confirmado (receita 1,48) para quem já está dentro e o \"VIP list ends today\" de 23/11/2025 para quem ainda não entrou. Dois públicos, duas notícias, nenhuma promessa repetida.",booster=None),
dict(data="2026-11-24",hora="10:00",janela="Black Week (25 a 29/11)",contexto="Black Week",papel="Antecipação 4 de 4: véspera com checklist",
 nome="Checklist da Black Week",publico=E90,
 oferta="Nenhuma nova. Mostra o que já está com preço reduzido.",
 assunto="Amanhã começa a Black Week. Você está pronto?",assunto_en="Black Week starts tomorrow. Are you ready?",
 pre="00h para a lista VIP, 7h para todos. O primeiro dia tem só 24 produtos.",
 hero="Amanhã: 24 horas, 24 produtos",sub="O primeiro dia da Black Week tem a oferta mais curta da semana. Quem se preparar leva.",
 blocos=["Agenda dos 5 dias em linha","Checklist: alarme · endereço · favoritos salvos · cartão salvo","\"Já no preço\": 4 produtos","\"Te vejo à meia-noite\""],
 cta="Ver o que já está no preço",urgencia="Amanhã às 00h (VIP) e 7h (todos).",
 ref=["check25","vespera88"],conexao="Mesma véspera com checklist do 10.10 e do 11.11, a versão de véspera que vende.",booster=None,
 canais="SMS/WhatsApp 18h: \"Amanhã começa a Black Week. 24 produtos só no primeiro dia.\""),
# ===== BLACK WEEK: dias =====
dict(data="2026-11-25",hora="00:00",janela="Black Week (25 a 29/11)",contexto="Black Week, dia 1: 24 horas, 24 produtos",papel="Pico: acesso antecipado VIP",
 nome="A Black Week começou para você",publico={"A":"VIP-BLACK + compradores do 11.11","B":"VIP-BLACK + compradores do 11.11","C":"VIP-BLACK + compradores do 11.11"},
 oferta="25% OFF nos 24 mais vendidos com o cupom BLACKWEEK (só hoje) + frete expresso grátis para a lista. Resto do site até 50%.",
 assunto="🔓 Sua Black Week começou antes",assunto_en="🔓 Your Black Week started early",
 pre="24 horas, 24 produtos, 25% OFF. A lista entra agora.",
 hero="Black Week chegou · 24 horas | 24 produtos · 25% OFF",sub="Cupom BLACKWEEK · só hoje · frete expresso grátis para a lista",
 blocos=["\"O grande dia chegou: 24 horas, 24 produtos, 25% OFF adicional\"","\"É simples\" em 4 passos","Grade com os 24 (ou 4 + \"ver os 24\"), cada um com a barra \"[X]% já vendido\" (dado real, como nas ofertas relâmpago do Mercado Livre e da Amazon)","\"A Black Week continua nos outros dias, mas os 25% nos 24 favoritos são só de hoje\""],
 cta="Ver os 24",urgencia="Só até 23h59 de hoje.",
 ref=["bw24_25","early25"],conexao="O primeiro dia da Black Week de 2025 (24 produtos, 24 horas), com o cupom subindo de 20% para 25% para ficar acima do 22% do 11.11. Oferta do dia com prazo curto, na primeira tela.",
 booster=None),
dict(data="2026-11-25",hora="07:00",janela="Black Week (25 a 29/11)",contexto="Black Week, dia 1",papel="Pico: disparo 1 (público)",
 nome="A Black Week começou (texto de pessoa)",publico=BFD,
 oferta="25% OFF nos 24 mais vendidos com BLACKWEEK, só hoje. Resto do site até 50%.",
 assunto="A oferta do ano começou ✅",assunto_en="Our offer of the year has started ✅",
 pre="Hoje: 24 produtos com 25% OFF. Amanhã, outra oferta.",
 hero="Texto puro, remetente pessoa",sub="",
 blocos=["\"Oi, [nome]. A Black Week começou e vai até domingo.\"","\"Hoje é o dia mais curto: 24 produtos com 25% OFF usando o cupom **BLACKWEEK**, só até 23h59.\"","\"Amanhã entra outra oferta, e estes 24 voltam ao preço da semana.\" [link]","Assinatura + P.S. com a agenda dos 5 dias"],
 cta="Link no texto",urgencia="Até 23h59.",
 ref=["cupom99"],conexao="O 07h em texto, validado no 9.9 e na Clube Rock, com a oferta do dia.",booster=None,
 canais="SMS/WhatsApp 07h05: \"Black Week no ar: 24 produtos, 25% OFF só hoje. [link]\""),
dict(data="2026-11-25",hora="18:00",janela="Black Week (25 a 29/11)",contexto="Black Week, dia 1",papel="Pico: principal do dia",
 nome="Status mudou (conversa)",publico=BFD,
 oferta="Últimas horas dos 25% nos 24 mais vendidos (BLACKWEEK).",
 assunto="🚨 Seu status acaba de mudar",assunto_en="🚨 Your status has just changed",
 pre="Os 24 voltam ao preço da semana à meia-noite.",
 hero="Conversa de celular",sub="",
 blocos=["Conversa: \"Os 24 da Black Week estão com 25%, só hoje\" · \"Já peguei 2. O [produto] acabou à tarde\" · \"Ainda dá?\" · \"Dá, mas meia-noite muda\"","Cupom BLACKWEEK","\"Ainda dá tempo\": 4 dos 24","Garantias"],
 cta="Aproveitar agora",urgencia="Até 23h59.",
 ref=["conversa88"],conexao="O 18h de maior índice da carteira, no primeiro dia da semana mais importante do ano.",
 booster=dict(quando="21h30 (delay de 3h30)",para="nonOpeners",assunto="🚨 [ÚLTIMA CHAMADA] Os 24 da Black Week mudam de preço à meia-noite")),
dict(data="2026-11-26",hora="10:00",janela="Black Week (25 a 29/11)",contexto="Black Week, dia 2: por coleção e por preço (Thanksgiving no global)",papel="Oferta do dia",
 nome="Desconto escondido: por coleção e por preço",publico=BFD,
 oferta="Até 60% no site + 20% extra com o cupom BLACKWEEK, até domingo. Navegação por coleção e por faixa de preço.",
 assunto="(1) desconto escondido para [nome] neste e-mail 🤫",assunto_en="(1) hidden discount for [name] inside this email 🤫",
 pre="Toque em \"revelar\" e veja quanto você economiza.",
 hero="Papel rasgado revelando \"+20% extra\" sobre \"até 60% OFF\"",sub="Cupom BLACKWEEK e validade logo abaixo.",
 blocos=["Revelação na primeira tela com o botão \"Revelar agora\"","\"Compre por coleção\": 4 coleções com foto","\"Compre por preço\": até [valor 1] · até [valor 2] · até [valor 3] · até [valor 4]","No global: faixa de Thanksgiving no topo"],
 cta="Revelar agora",urgencia="Até domingo às 23h59.",
 ref=["revele","bwcol25"],conexao="O Revele abriu a Mid-Year Black com o recorde de pedidos da Blue Wolf (18) e tem assunto com receita 1,50. O corpo usa o \"shop by collection / shop by price\" de 25/11/2025. Oferta grande, e-mail curto, tudo na primeira tela.",booster=None),
dict(data="2026-11-26",hora="18:00",janela="Black Week (25 a 29/11)",contexto="Black Week, dia 2",papel="Mesma oferta, formato novo",
 nome="A Black está te ligando",publico=BFD,
 oferta="Até 60% + 20% extra (BLACKWEEK). Amanhã é o dia da Black Friday.",
 assunto="[Nome], você tem uma chamada recebida 📞",assunto_en="[Name], you have an incoming call 📞",
 pre="Atenda rápido. Amanhã o preço muda de novo.",
 hero="\"Sua chance está te ligando...\" · celular com a chamada da Black Week",sub="Botões recusar e atender, CTA \"Atender\".",
 blocos=["Oferta dentro da tela do celular: \"até 60% + 20% extra · BLACKWEEK\"","\"Os produtos na linha\": 4 produtos","\"Amanhã é sexta: a Black Friday tem uma oferta própria\""],
 cta="Atender",urgencia="Até domingo.",
 ref=["ligacao"],conexao="Mesma oferta em formato novo vende de novo: revelação, jornal e ligação somaram 44 pedidos na Mid-Year Black. Ligação: 1,17 na amostra ampla.",booster=None),
dict(data="2026-11-27",hora="07:00",janela="Black Week (25 a 29/11)",contexto="Black Friday",papel="Pico: disparo 1",
 nome="Hoje é o dia (texto de pessoa)",publico=BFD,
 oferta="Até 60% no site + 25% extra com o cupom BLACK, só hoje. Brinde surpresa nos pedidos de hoje.",
 assunto="[Nome], hoje é o dia",assunto_en="[Name], today is the day",
 pre="A maior oferta do ano, só até 23h59.",
 hero="Texto puro, remetente pessoa",sub="",
 blocos=["\"Oi, [nome]. Hoje é Black Friday, e é a oferta mais forte do ano.\"","\"Até 60% no site e mais **25% extra** com o cupom **BLACK**. Todo pedido de hoje leva um brinde surpresa.\"","\"Vale só até 23h59. Amanhã o desconto é outro.\" [link]","Assinatura"],
 cta="Link no texto",urgencia="Só hoje.",
 ref=["cupom99","bf1_25"],conexao="Texto de 07h validado + a oferta do dia principal de 2025 (50% + 23% extra), agora com 25% extra para ser a maior do trimestre.",booster=None,
 canais="SMS/WhatsApp 07h05: \"Black Friday: até 60% + 25% extra com BLACK, só hoje.\""),
dict(data="2026-11-27",hora="11:00",janela="Black Week (25 a 29/11)",contexto="Black Friday",papel="Pico: disparo 2",
 nome="Seu presente de Black Friday chegou",publico=BFD,
 oferta="25% extra com BLACK + brinde surpresa em todo pedido de hoje.",
 assunto="Seu presente de Black Friday chegou 🎁",assunto_en="Your Black Friday gift has arrived 🎁",
 pre="Não é uma compra. É um presente, e só vale hoje.",
 hero="Black Friday · brinde surpresa no pedido · 25% extra",sub="Cupom BLACK na primeira tela.",
 blocos=["\"Seu presente de Black Friday chegou... e não, não é uma compra. É algo melhor: um brinde em todo pedido de hoje.\"","Grade 2x2","Faixa \"Black Friday exclusiva por e-mail\" com o cupom","Grade 2x1 + garantias"],
 cta="Pegar meu desconto",urgencia="Só hoje.",
 ref=["bf2_25"],conexao="Segundo disparo da BF de 2025, com o brinde surpresa como notícia nova do dia. A oferta fica na primeira tela, que é a regra do 11h que funciona.",booster=None),
dict(data="2026-11-27",hora="18:00",janela="Black Week (25 a 29/11)",contexto="Black Friday",papel="Pico: principal do dia",
 nome="Status mudou (conversa)",publico={"A":"LT (2 de 2)","B":"LT (única do nível)","C":"E90"},
 oferta="Até 60% + 25% extra com BLACK, até 23h59.",
 assunto="🚨 Seu status acaba de mudar",assunto_en="🚨 Your status has just changed",
 pre="Faltam 6 horas para a maior oferta do ano acabar.",
 hero="Conversa de celular",sub="",
 blocos=["Conversa: \"Black Friday com 25% extra, cupom BLACK\" · \"Já foi. E veio um brinde junto\" · \"Sério?\" · \"Só hoje, até meia-noite\"","Cupom BLACK + brinde","\"Ainda dá tempo\": 4 produtos","Garantias"],
 cta="Aproveitar agora",urgencia="Termina às 23h59.",
 ref=["conversa88"],conexao="O melhor 18h da carteira, no dia mais forte do ano, para o maior público do trimestre.",
 booster=dict(quando="21h30 (delay de 3h30)",para="nonOpeners",assunto="🚨 [ÚLTIMA CHAMADA] A Black Friday expira às 23h59"),
 canais="Push 18h: \"Status mudou\". SMS 20h30 para quem clicou e não comprou."),
dict(data="2026-11-28",hora="10:00",janela="Black Week (25 a 29/11)",contexto="Black Week, dia 4: monte seu kit",papel="Oferta do dia",
 nome="Monte seu kit",publico=BFD,
 oferta="Progressivo: 1 item 15% · 2 itens 20% · 3 ou mais 25% (BLACK15, BLACK20, BLACK25), até domingo. Os 100 primeiros pedidos com 3 itens ganham brinde.",
 assunto="Quanto mais você leva, maior o desconto",assunto_en="The more you buy, the bigger the discount",
 pre="15%, 20% ou 25%. E um brinde para os 100 primeiros.",
 hero="Monte seu kit · Quanto mais peças, maior o desconto",sub="15% · 20% · 25%, direto no carrinho.",
 blocos=["Três caixas com os percentuais e os cupons","\"Brinde exclusivo: os 100 primeiros pedidos com 3 itens\"","\"Economia que cresce com o carrinho\": combinações sugeridas","Grade de 4"],
 cta="Montar meu kit",urgencia="Até domingo às 23h59.",
 ref=["kit25"],conexao="O kit progressivo de 26/11/2025, com os percentuais subindo. Sábado da Black pede motivo novo para abrir: um desconto que depende do carrinho.",booster=None,teste="T3: fim de semana da Black com e-mail."),
dict(data="2026-11-28",hora="18:00",janela="Black Week (25 a 29/11)",contexto="Black Week, dia 4",papel="Fechamento com cara de pedido",
 nome="Notificação do futuro",publico=BFD,
 oferta="Kit progressivo até 25% ou até 60% + 25% extra, até domingo às 23h59.",
 assunto="[Nome], falta você confirmar esse pedido...",assunto_en="[Name], you still need to confirm your order...",
 pre="A Black Week termina amanhã às 23h59.",
 hero="Notificação do futuro · Seu pedido da Black está a caminho ✓",sub="Viemos do futuro avisar: você não deixou a Black passar.",
 blocos=["Fundo branco, aviso de sistema","Resumo de pedido simulado com o kit e o cupom aplicado","\"Termina amanhã, domingo, às 23h59\"","4 produtos"],
 cta="Confirmar meu pedido",urgencia="Termina amanhã.",
 ref=["notif"],conexao="Formato de fechamento (último dia do WEEK15), usado na véspera do fim da Black: 1,67 na amostra ampla, 3,61% de clique.",booster=None),
dict(data="2026-11-29",hora="10:00",janela="Black Week (25 a 29/11)",contexto="Black Week, dia 5: última chamada",papel="Oferta do dia",
 nome="Jornal: últimas horas da Black Week",publico=BFD,
 oferta="Até 60% + 25% extra com BLACK, até 23h59.",
 assunto="[Nome], chegou a notícia que você não queria...",assunto_en="[Name], the news you did not want to hear has arrived...",
 pre="A Black Week termina hoje às 23h59.",
 hero="Breaking news · domingo, 29 de novembro · a Black Week termina hoje",sub="Até 60% + 25% extra com o cupom BLACK, até 23h59.",
 blocos=["Cabeçalho de jornal com a data","Cupom BLACK","Foto da embalagem","\"Os destaques da manchete\""],
 cta="Ver os destaques",urgencia="Até 23h59.",
 ref=["jornal22"],conexao="Jornal de fechamento de semana grande (Mid-Year Black: 1,62 nas 9 lojas).",booster=None),
dict(data="2026-11-29",hora="18:00",janela="Black Week (25 a 29/11)",contexto="Black Week, dia 5",papel="Pico: fechamento",
 nome="Last call",publico=BFD,
 oferta="Até 60% + 25% extra com BLACK, até 23h59.",
 assunto="🚨 [ÚLTIMA CHAMADA] Expira às 23h59",assunto_en="🚨 [FINAL CALL] Expires at 11:59 PM",
 pre="A maior oferta do ano acaba à meia-noite.",
 hero="Última chamada · Black Week · 25% extra · cupom BLACK",sub="Expira hoje às 23h59.",
 blocos=["Número, cupom e prazo na primeira tela","\"A Black está acabando. Mais algumas horas. Meia-noite...\"","4 produtos","Linha do tempo dos 5 dias com o último em destaque"],
 cta="Usar antes que acabe",urgencia="Meia-noite.",
 ref=["lastcall77"],conexao="O last call do 7.7 (US$ 105,3 por mil, 3,06% de clique, 1,22 na amostra ampla) é o formato de fechamento da carteira.",
 booster=dict(quando="21h30 (delay de 3h30)",para="nonOpeners",assunto="⏳ A Black Week acaba em 2 horas"),
 canais="SMS/WhatsApp 20h30 para quem clicou e não comprou."),
# ===== CYBER MONDAY =====
dict(data="2026-11-30",hora="07:00",janela="Cyber Monday (30/11 a 02/12)",contexto="Cyber Monday: o dia do combo",papel="Segundo evento com motivo próprio",
 nome="Cyber Monday: uma oferta que não estava na Black",publico=E90,
 oferta="Oferta nova: leve 3, pague 2 (ou kit fechado por [preço]) + frete grátis, até quarta, 02/12, às 23h59.",
 assunto="Cyber Monday: tem uma oferta que não estava na Black ✅",assunto_en="Cyber Monday: an offer that wasn't in Black Friday ✅",
 pre="Leve 3, pague 2. Até quarta.",
 hero="Texto puro, remetente pessoa",sub="",
 blocos=["\"Oi, [nome]. A Black acabou, e a Cyber Monday não é extensão dela.\"","\"Até quarta, você leva 3 e paga 2 (o de menor valor sai de graça), com frete grátis.\"","\"Isso não existia na Black Week.\" [link]","Assinatura"],
 cta="Link no texto",urgencia="Até quarta às 23h59.",
 ref=["cupom99","cm25"],conexao="A lição da carteira: segundo evento colado só rende com motivo e oferta novos (o Dia do Rock, com 3 camisetas por R$ 169 e frete grátis, rendeu quase o mesmo que o 7.7; o Dia do Cliente, que repetiu a mecânica, caiu 47%). A CM de 2025 foi extensão do cupom: não repetir.",booster=None,
 canais="SMS/WhatsApp 07h05: \"Cyber Monday: leve 3, pague 2 até quarta.\""),
dict(data="2026-11-30",hora="18:00",janela="Cyber Monday (30/11 a 02/12)",contexto="Cyber Monday",papel="Principal do dia",
 nome="Status mudou (conversa)",publico={"A":"E180","B":"E90","C":"E90"},
 oferta="Leve 3, pague 2 + frete grátis, até quarta.",
 assunto="🚨 Seu status acaba de mudar",assunto_en="🚨 Your status has just changed",
 pre="Leve 3, pague 2. Isso não tinha na Black.",
 hero="Conversa de celular",sub="",
 blocos=["Conversa: \"Na Cyber o 3º sai de graça\" · \"Montei o meu com o que eu não peguei na Black\" · \"Até quando?\" · \"Quarta\"","Mecânica \"leve 3, pague 2\"","Combinações sugeridas","Garantias"],
 cta="Montar meu combo",urgencia="Até quarta.",
 ref=["conversa88"],conexao="Formato de maior índice no 18h, com a oferta nova da CM.",
 booster=dict(quando="21h30 (delay de 3h30)",para="nonOpeners",assunto="A Cyber Monday tem uma oferta que não estava na Black")),
]
