E90={"A":"E90","B":"E90","C":"E90"}
SEL={"A":"SELECIONADOS-1111","B":"SELECIONADOS-1111","C":"SELECIONADOS-1111"}
NOV_A=[
# ================= ATO 4: O FUNDADOR ENTRA (sequência de 2025) =================
dict(data="2026-11-01",hora="10:00",janela="Halloween da [Gerente] (29/10 a 01/11)",contexto="A [Gerente] encerra o Halloween e dá um presente",papel="Virada (e-mail 03 de 2025)",
 nome="Última chance de Halloween + um presentinho",publico=E90,
 oferta="Cupom HALLOWEEN15 (15% no site), só hoje até 23h59, como agradecimento da [Gerente].",
 assunto="Última chance de Halloween + um presentinho especial pra você",assunto_en="Last chance for Halloween + a little gift just for you",
 pre="A promoção acabou. Mas eu separei uma coisa para você.",
 hero="Texto da [Gerente]",sub="",
 blocos=["\"Oi, [nome]. Aqui é a [Gerente].\"",
  "\"A Promoção Progressiva de Halloween terminou oficialmente ontem à meia-noite. Foi o mês mais movimentado do ano até agora, e eu queria agradecer quem acompanhou.\"",
  "\"Então fiz uma coisa que talvez eu não devesse: liberei um cupom de 15% só para quem está nesta lista, válido até hoje às 23h59. Use **HALLOWEEN15** no checkout.\"",
  "\"USAR MEU PRESENTE >>>\"",
  "\"Um beijo, [Gerente]\""],
 cta="USAR MEU PRESENTE >>>",urgencia="Só hoje.",
 hero_tipo="Texto puro",hv="e-mail só de texto assinado pela gerente",
 est="Saudação pelo nome → encerramento oficial da promoção → presente com cupom em negrito → link → assinatura calorosa",
 ideia="É o ponto de virada de 2025: a gerente, generosa, dá um presente por conta própria. O \"talvez eu não devesse\" planta o conflito de amanhã.",
 historia="Ato 3, fim. A [Gerente] age por conta própria pela segunda vez (depois da reabertura de 24/10). Loop aberto: o que o [Fundador] vai achar disso?",
 ref=["reabertura"],conexao="É o e-mail 03 da sequência de 2025, que deu resultado na carteira (seção 15). Formato de texto assinado, o mesmo da reabertura de 25/07 (1,15 na amostra ampla).",
 booster=None,canais="WhatsApp ou SMS com o cupom às 10h05."),
# ================= ATO 4: O FUNDADOR ENTRA (2025 + antecipações de 7.7, 8.8 e 9.9, em 5 e-mails) =================
dict(data="2026-11-02",hora="10:00",janela="11.11 Black Antecipada",contexto="O [Fundador] acaba com as promoções improvisadas e anuncia o calendário: Black Antecipada no dia 11, só para a lista selecionada",papel="Fase 1 · Antecipar (pré-lançamento): carta do fundador + cartão de convite do 7.7",
 nome="Comunicado do fundador",publico={"A":"E365","B":"E180","C":"E90"},
 oferta="Nenhuma neste e-mail. Anuncia a Black Antecipada (11/11) e avisa que, até lá, alguns produtos já vão estar com condição especial no site, sem cupom (até 30%, de 04 a 10/11). Cria a lista selecionada: para entrar, a pessoa clica em \"Confirmar minha vaga\", responde o e-mail ou deixa o telefone no pop-up (grava SELECIONADOS-1111). Quem entrou na lista de espera em 15/10 já está dentro.",
 assunto="Comunicado oficial sobre as promoções da [Loja]",assunto_en="Official notice about [Store]'s promotions",
 assuntos3=["Conservador: Comunicado oficial sobre as promoções da [Loja]","Equilibrado: [Nome], a partir de hoje a Black tem calendário","Ousado: [Nome], eu cancelei as nossas promoções"],
 pre="Uma decisão que eu tomei hoje de manhã, e o que ela muda para você.",
 hero="Texto do [Fundador], formal",sub="",
 blocos=["\"Prezado(a) [nome],\"",
  "\"Sou o [Fundador], fundador da [Loja]. Escrevo para comunicar uma decisão.\"",
  "\"Nas últimas semanas, a nossa equipe reabriu promoções e liberou cupons fora do calendário, incluindo o de ontem. A intenção foi boa. Mas a partir de hoje, acabou o improviso: a nossa Black vai ter calendário.\"",
  "\"No dia 11 abrimos a Black Antecipada: 24 horas, os 24 produtos mais vendidos, com a maior condição que já oferecemos antes da Black Friday. Até lá, sem cupom improvisado: a partir de quarta, alguns produtos já vão estar com condição especial no site, e é só isso.\"",
  "\"A Black Antecipada terá acesso restrito a uma lista selecionada, que entra à meia-noite, sete horas antes do público. Como forma de pedir desculpas pela confusão, reservei uma vaga para você. Para confirmar, basta clicar abaixo. CONFIRMAR MINHA VAGA >>>\"",
  "\"Atenciosamente, [Fundador], fundador da [Loja]\"",
  "Abaixo da assinatura, o CARTÃO DE CONVITE do 7.7 (única imagem do e-mail): \"Você está oficialmente convidado · 11.11 Black Antecipada · 00h · 07h · 11h · 18h\" + botão \"CONFIRMAR MINHA VAGA\" + barra \"Seu convite: enviado › lido › confirmado\""],
 cta="CONFIRMAR MINHA VAGA >>>",urgencia="As vagas são confirmadas até 10/11.",
 hero_tipo="Carta do fundador + cartão de convite",hv="cartão de convite no estilo do e-mail de 01/07 do 7.7: selo \"Você está oficialmente convidado\", título \"11.11 Black Antecipada\", as pílulas de horário 00h, 07h, 11h e 18h, o botão \"Confirmar minha vaga\" e a barra de status enviado, lido, confirmado",
 prompt_custom="Gerar só o cartão de convite (o resto do e-mail é texto no editor da Omnisend). Imagem de 600 px de largura com a identidade da [NOME DA LOJA]: selo \"Você está oficialmente convidado\", título \"11.11 Black Antecipada\", pílulas de horário \"00h · 07h · 11h · 18h\", botão \"CONFIRMAR MINHA VAGA\" e uma barra de status com três etapas: enviado, lido, confirmado. Textos em português do Brasil, sem travessão.",
 est="Carta formal em texto: saudação → a decisão (acabou o improviso) → a Black Antecipada no dia 11 e a condição especial até lá → a lista que entra à meia-noite → a vaga reservada como pedido de desculpas → link de confirmação → assinatura → cartão de convite do 7.7 com a barra de status",
 ideia="A carta do CEO de 2025 (o texto que abre a história) seguida do cartão de convite do 7.7 (o design da antecipação de maior índice). O texto dá o motivo; o cartão dá o clique.",
 historia="Ato 4, capítulo 1. O [Fundador] troca o improviso da [Gerente] por um calendário e cria a lista. Gancho: a vaga na lista.",
 ref=["reabertura","convite77"],conexao="O conteúdo é a carta do CEO de 2025 (seção 15.1). O \"não compre nada\" sai porque a condição especial fica ativa no site, e as duas coisas não convivem. O formato é o texto assinado da reabertura de 25/07 (1,15 na amostra ampla). A confirmação por clique é o convite do 7.7 (1,55 nas 9 lojas) e a correção de 2026 do estudo (15.9). Público mais largo de propósito: é o e-mail que reengaja quem vai receber o 07h do dia 11.",
 booster=None,canais="Pop-up \"lista selecionada do 11.11\" no ar a partir de hoje, com e-mail e telefone."),
dict(data="2026-11-04",hora="10:00",janela="11.11 Black Antecipada",contexto="Está chegando: o 11.11 e a lista VIP",papel="Fase 2 · Gerar desejo: teaser do 11.11 + você está na lista VIP + catálogo",
 nome="Está chegando. E você está na lista VIP.",publico={"A":"E90 + SELECIONADOS-1111","B":"E90 + SELECIONADOS-1111","C":"E90 + SELECIONADOS-1111"},
 oferta="Anuncia o dia 11 (até 50% + 22% extra, 24 horas, 24 produtos). Catálogo com os produtos que já estão com condição especial no site, sem cupom (até 30%, até 10/11).",
 assunto="[Nome], você está na lista VIP (e não pagou nada por isso) ✅",assunto_en="[Name], you're on the VIP list (and it didn't cost you a thing) ✅",
 assuntos3=["Conservador: [Nome], você já viu o que está vindo? 👀","Equilibrado: [Nome], você está na lista VIP (e não pagou nada por isso) ✅","Ousado: Faltam 7 dias. Você está dentro."],
 pre="11/11, meia-noite: o site abre primeiro para a lista. Faltam 7 dias.",
 hero="Está chegando · 11.11",sub="A maior condição que já demos antes da Black, por 24 horas. E você está na lista de quem entra primeiro.",
 blocos=["Faixa de topo em marquee: \"SAVE THE DATE 11.11 ✦ SAVE THE DATE 11.11\" (bloco dos e-mails de 2025)",
  "Hero (do 9.9, 05/09): \"ESTÁ CHEGANDO\" + folha de calendário de novembro com o dia 11 circulado + \"BLACK ANTECIPADA · 24 horas com a maior condição antes da Black\" + botão \"QUERO ME PREPARAR\"",
  "Selo (de 2025, 05/11): \"VOCÊ ESTÁ NA LISTA VIP · acesso antecipado garantido\" (quem confirmou) ou \"Sua vaga está reservada · falta confirmar\" com o botão (quem não confirmou)",
  "Hook de desejo (2025): \"Imagine abrir o site à meia-noite do dia 11 e encontrar aquilo que você quer há meses com o maior desconto do ano. Sem fila, sem estoque esgotado.\"",
  "\"Por que não dá para perder\" (4 motivos, 2025): a maior condição antes da Black · os 24 mais vendidos · entrada 7 horas antes do público · uma vez por ano",
  "\"Quatro horários em um dia\" (do 9.9): 00h · 07h · 11h · 18h. \"O que vem em cada horário você ainda vai descobrir.\"",
  "CATÁLOGO: \"Já com condição especial no site\" (copy real do 8.8: \"já tem condição especial no site agora mesmo\"): grade 2x3 com preço de antes e de agora + \"VER TODOS\"",
  "\"Como garantir o seu desconto no dia 11\" (3 passos, 2025): de hoje até 10/11, escolha e deixe no carrinho · dia 10, alarme às 23h55 · à meia-noite, finalize rápido",
  "\"Faltam 7 dias\" + P.S.: \"Qual produto você está esperando? Responde este e-mail, eu leio todos.\""],
 cta="QUERO ME PREPARAR",urgencia="Faltam 7 dias. Condição especial até 10/11.",
 hero_tipo="Calendário com o dia circulado",hv="hero \"Está chegando\" com a folha de calendário de novembro e o dia 11 circulado, como o e-mail de 05/09 do 9.9, e logo abaixo o selo \"Você está na lista VIP\"",
 est="Marquee save the date → hero de calendário → selo da lista VIP → hook \"Imagine\" → 4 motivos → quatro horários → catálogo com condição especial → 3 passos → contagem e pedido de resposta → garantias",
 ideia="É o teaser: anuncia o 11.11, diz para a pessoa que ela está dentro e mostra o que ela já pode comprar hoje. Estrutura do melhor esquenta do 9.9 com o selo, os motivos e os passos do anúncio de 2025, sem chamar de esquenta.",
 historia="Ato 4, capítulo 2. O calendário do [Fundador] vira privilégio: \"você está na lista\".",
 ref=["cal99","anuncio25"],conexao="O hero é o do 05/09 do 9.9, o melhor dos quatro esquentas (12 pedidos), com a copy real da versão Brasil. O selo, os 4 motivos e os 3 passos são do primeiro e-mail do board de 2025 (05/11). O catálogo com condição especial é a seção que fez a antecipação do 8.8 e do 9.9 vender sem cupom (46% e 70% da receita do pico na Blue Wolf). O assunto equilibrado junta o \"você está na lista. De graça\" de 2025 com o ✅ dos assuntos de confirmação que mais vendem.",
 booster=None,canais="Push: \"Você está na lista do dia 11.\""),
dict(data="2026-11-06",hora="10:00",janela="11.11 Black Antecipada",contexto="Prova e quebra de objeção",papel="Fase 3 · Quebrar objeções: prova (2025) + Nós x Eles (2025)",
 nome="Estes esgotam primeiro, e aqui a Black é diferente",publico={"A":"E90 + SELECIONADOS-1111","B":"E90 + SELECIONADOS-1111","C":"E90 + SELECIONADOS-1111"},
 oferta="Condição especial ativa no site (até 30%, sem cupom, até 10/11). Mostra os produtos que sempre esgotam, com estoque real, e prova que o preço do dia 11 é real.",
 assunto="Estes sempre esgotam primeiro (e dá para provar que o preço é real)",assunto_en="These always sell out first (and we can prove the price is real)",
 assuntos3=["Conservador: Estes são os que sempre esgotam primeiro","Equilibrado: Estes sempre esgotam primeiro (e dá para provar que o preço é real)","Ousado: Não vai ter \"vou pensar depois\""],
 pre="Acabamos de conferir o estoque. E respondemos a pergunta que todo mundo faz.",
 hero="Estes sempre esgotam primeiro",sub="Oi, [nome]. Aqui é a equipe da [Loja]. Acabamos de conferir o estoque da Black Antecipada, e tem duas coisas que você precisa saber antes do dia 11.",
 blocos=["PARTE 1, A PROVA: \"Estes são os produtos que sempre esgotam primeiro\": os 6 principais com estoque atual e uma prova por item (só números verdadeiros: \"esgotou em [tempo] no 10.10\", \"[N] avaliações nota 10\")",
  "\"Por que estou te mostrando isso? Porque no dia 11 não vai ter 'vou pensar depois'. Vai ser: vi, gostei, cliquei, comprei.\"",
  "Separador visual",
  "PARTE 2, A DIFERENÇA: \"Você já viu produto que 'baixou 50%' e custava o mesmo em outubro?\"",
  "Tabela \"[Loja] x outras lojas\" com 5 critérios verificáveis: preço dos últimos 30 dias à mostra · troca garantida · envio com rastreio em [prazo] · pagamento seguro · atendimento que responde",
  "\"Já com condição especial no site\": 4 produtos",
  "Fechamento: \"11/11, meia-noite para a lista. Sua vaga: [status].\" + \"Faltam 5 dias\" + P.S. com gancho: \"Domingo eu te conto o bônus que só os 100 primeiros vão levar.\""],
 cta="SALVAR MEUS FAVORITOS",urgencia="Faltam 5 dias.",
 hero_tipo="Hero de produto com estoque",hv="grade de 6 produtos com uma barra de estoque em cada, sob o título \"Estes sempre esgotam primeiro\"; mais abaixo, uma tabela comparativa com checks e X",
 est="Abertura da equipe → parte 1: grade dos 6 com estoque e prova → por que estou mostrando → separador → parte 2: pergunta de objeção → tabela de 5 critérios → já com condição especial → status da vaga e contagem → P.S. com gancho → garantias",
 ideia="Junta a tangibilização e o Nós x Eles de 2025, os dois que respondem \"vale a pena esperar?\" e \"o desconto é real?\". O catálogo com condição especial dá o que comprar hoje para quem já está convencido.",
 historia="Ato 4, capítulo 3. Deixa a oferta concreta, tira a última objeção e abre o loop do bônus.",
 ref=["prova25","nosxeles25"],conexao="São os e-mails 07/11 e 09/11 do board de 2025 (\"These are the 6 products that always sell out\" e \"Our differential\"), fundidos em um. O estudo pede números reais e critérios verificáveis (o \"73%\" de 2025 não tinha fonte).",
 booster=None),
dict(data="2026-11-08",hora="10:00",janela="11.11 Black Antecipada",contexto="Faltam 3 dias: como funciona, o bônus e o acesso",papel="Fase 4 · Antecipar de novo: faltam 3 dias (8.8) + os momentos do dia (7.7) + bônus e garantia (2025) + acesso confirmado (6.6)",
 nome="Faltam 3 dias",publico={"A":"Duas versões: SELECIONADOS-1111 · demais E90","B":"Duas versões: SELECIONADOS-1111 · demais E90","C":"Duas versões: SELECIONADOS-1111 · demais E90"},
 oferta="Condição especial ativa no site (até 30%, sem cupom, até 10/11). Revela os bônus do dia 11: progressivo de 10%, 15% e 20% extra para os 100 primeiros pedidos com 2 ou mais itens, frete prioritário para a lista e troca garantida.",
 assunto="Faltam 3 dias e 60% das pessoas me perguntaram isso",assunto_en="3 days left and 60% of people asked me this",
 assuntos3=["Conservador: [Nome], seu acesso está confirmado ✅","Equilibrado: Faltam 3 dias e 60% das pessoas me perguntaram isso","Ousado: 7 horas de vantagem (e um bônus que só 100 pessoas levam)"],
 pre="Como vai funcionar, o bônus que só os 100 primeiros levam e a sua vaga.",
 hero="Faltam 3 dias",sub="No dia 11, você só confirma.",
 blocos=["Hero (do 8.8): \"FALTAM 3 DIAS · no dia 11, você só confirma\" + botão \"QUERO ME PREPARAR\"",
  "Status da vaga no topo: \"Acesso confirmado: meia-noite do dia 11\" (confirmados) ou \"⚠️ Sua vaga ainda não foi confirmada\" com o botão (demais; assunto da versão: \"⚠️ [Nome], sua vaga ainda não foi confirmada\")",
  "Copy real do 8.8, adaptada: \"Quem deixa para a última hora já sabe como termina: sem estoque, sem o que queria, sem tempo. Agora é a hora de abrir o site, escolher com calma e deixar tudo separado. Quando o dia chegar, você só finaliza. E tem mais: já tem condição especial no site agora mesmo.\"",
  "\"OS 4 MOMENTOS DO 11.11\" (a agenda do 7.7, com a explicação do 8.8 e do 9.9): 00h ACESSO ANTECIPADO · o site abre só para a lista, com estoque cheio, sete horas antes do público · 07h ABERTURA GERAL · 11h CLUBE VIP · 18h ÚLTIMA CHAMADA · depois disso, as condições saem do ar + barra de status da vaga (7.7)",
  "Educação curta e regra de ouro (2025): \"60% das pessoas me perguntaram como aproveitar de verdade. Regra de ouro: escolha antes, compre no primeiro horário, não espere o estoque decidir por você.\" + \"E se não servir? Troca garantida em [prazo]. O risco é nosso.\"",
  "\"BÔNUS REVELADOS\": progressivo 10% · 15% · 20% extra para os 100 primeiros pedidos com 2 ou mais itens · frete prioritário para a lista · troca garantida (caixas grandes)",
  "\"Já com condição especial no site\": 4 produtos"],
 cta="Confirmados: QUERO ME PREPARAR · Demais: CONFIRMAR MINHA VAGA",urgencia="Faltam 3 dias.",
 hero_tipo="Contagem de dias",hv="hero com \"Faltam 3 dias\" em letras grandes e a frase \"no dia 11, você só confirma\", como o e-mail de 05/08 do 8.8; mais abaixo, três caixas de bônus 10%, 15% e 20%",
 est="Hero de contagem → status da vaga → copy do 8.8 (quem deixa para a última hora) → os 4 momentos do dia com a barra de status do 7.7 → educação curta, regra de ouro e troca garantida → bônus em caixas → já com condição especial → garantias",
 ideia="O \"faltam 3 dias\" do 8.8, o melhor esquenta de agosto em receita, com a parte mais Hormozi de 2025 (regra de ouro, garantia e bônus empilhados) e o acesso confirmado do 6.6. Quem não confirmou recebe a pendência, o formato que vende melhor que o \"acesso pendente\" da véspera do 7.7.",
 historia="Ato 4, capítulo 4. Fecha o loop do bônus aberto no P.S. de 06/11 e confirma quem entra à meia-noite.",
 ref=["esq88b","agenda77","bonus25"],conexao="A agenda do 7.7 (\"os 3 momentos\", barra de status) foi a antecipação de maior abertura de 2026 (44,3%) e vendeu mais que o 07h do dia. O 05/08 do 8.8 (\"faltam 3 dias\", \"como vai funcionar\") teve 0,78 nas 9 lojas, o melhor esquenta do 8.8 em receita; a copy real da versão Brasil está na ficha. O bônus progressivo para os 100 primeiros e a abertura dupla do assunto são do híbrido de 2025 (08/11). Acesso confirmado: receita 1,48 (3 de 3); pendência: 1,52.",
 booster=None),
dict(data="2026-11-10",hora="10:00",janela="11.11 Black Antecipada",contexto="É amanhã, e a condição especial acaba hoje",papel="Fase 5 · Antecipar e preparar a venda: é amanhã (9.9) + checklist (8.8) + preparação final (2025)",
 nome="É amanhã",publico={"A":"E180 + SELECIONADOS-1111","B":"E180 + SELECIONADOS-1111","C":"E90 + SELECIONADOS-1111"},
 oferta="Último dia da condição especial no site (até 30%, sem cupom, até 23h59). Revelação final dos 5 produtos que entram amanhã, com estoque.",
 assunto="Menos de 24 horas",assunto_en="Less than 24 hours",
 assuntos3=["Conservador: Amanhã é 11.11. Você está pronto?","Equilibrado: Menos de 24 horas","Ousado: Amanhã, à meia-noite, o site abre só para você"],
 pre="A lista entra à meia-noite. O público, às 7h.",
 hero="É amanhã",sub="A maior oferta antes da Black, nos seguintes horários: 00h · 07h · 11h · 18h.",
 blocos=["Hero (do 9.9): \"É AMANHÃ · a maior oferta antes da Black · nos seguintes horários\" com as pílulas 00h · 07h · 11h · 18h + botão \"QUERO PREPARAR MEU CARRINHO\"",
  "Faixa: \"A condição especial de hoje acaba às 23h59. À meia-noite, entra a Black Antecipada.\"",
  "\"Amanhã é o dia\" (copy real do 9.9, adaptada): \"À meia-noite, os 24 mais vendidos entram na maior oferta que já fizemos antes da Black. O que vai fazer diferença não é a velocidade, é chegar sabendo o que você quer. Quem entra com o carrinho montado sai na frente. Hoje é o dia de escolher. Amanhã é o dia de fechar.\"",
  "\"Pronto para amanhã?\" (checklist do 8.8): ☐ Anotou os horários? · ☐ Colocou o alarme às 23h55? · ☐ Já escolheu o que vai levar? · ☐ Salvou o cartão no site?",
  "\"Ainda com dúvida?\" (FAQ do 9.9): Preciso de cadastro especial? Não, quem confirmou a vaga já está na lista · E se eu não conseguir à meia-noite? Tem 7h, 11h e 18h, mas alguns produtos podem acabar · Vale para o site todo? · Vai ter prorrogação? Não.",
  "\"O que entra na oferta de amanhã\" (revelação final de 2025): os 5 principais com o estoque de hoje",
  "Bilhete (do 9.9): \"HOJE 10/11 → AMANHÃ 11/11 · FALTA 1 DIA\"",
  "P.S. triplo (2025): o horário · o cupom chega por e-mail · a vaga é pessoal"],
 cta="QUERO PREPARAR MEU CARRINHO",urgencia="Amanhã, 00h.",
 hero_tipo="Contagem com horários",hv="hero com \"É amanhã\" em letras grandes, \"a maior oferta antes da Black\" e as quatro pílulas de horário, como o e-mail \"It's tomorrow\" do 9.9, com uma faixa \"a condição especial acaba hoje\"",
 est="Hero \"é amanhã\" com horários → faixa da condição especial que acaba hoje → \"amanhã é o dia\" → checklist → FAQ → os 5 que entram, com estoque → bilhete hoje/amanhã → P.S. triplo → garantias",
 ideia="A véspera junta os três que funcionaram (o \"It's tomorrow\" do 9.9, o checklist do 8.8 e a preparação final de 2025) e ganha um motivo para comprar hoje: a condição especial acaba à meia-noite, na mesma hora em que a Black Antecipada abre.",
 historia="Ato 4, capítulo 5. Fecha todos os loops antes do dia.",
 ref=["esq99b","vespera88"],conexao="O 08/09 do 9.9 foi o melhor e-mail do 9.9 na Emyerre; a copy real da versão Brasil está na ficha. A véspera com checklist foi o melhor esquenta do 8.8 (10 pedidos). A revelação final e o P.S. triplo são da preparação final de 2025. Segmento um pouco mais largo (E180 nos níveis A e B) para aquecer quem recebe o 07h.",
 booster=None,canais="SMS/WhatsApp 18h: \"Amanhã é 11.11. A lista entra à meia-noite.\""),
dict(data="2026-11-11",hora="00:00",janela="11.11 Black Antecipada",contexto="11.11 Black Antecipada",papel="Fase 6 · Vender: envio 1 de 5, acesso antecipado",
 nome="A lista selecionada entrou",publico={"A":"E30 + SELECIONADOS-1111","B":"E30 + SELECIONADOS-1111","C":"E30 + SELECIONADOS-1111"},
 oferta="Até 50% no site + 22% extra com o cupom BLACKVIP + bônus progressivo para os 100 primeiros, até 23h59. Só esta lista entra antes das 7h.",
 assunto="🔓 Sua Black começou antes",assunto_en="🔓 Your Black Friday started early",
 assuntos3=["Conservador: 🔓 Seu acesso antecipado foi liberado","Equilibrado: 🔓 Sua Black começou antes","Ousado: O site abriu. Só para você, até as 7h."],
 pre="Meia-noite: a lista entrou. O público só às 7h.",
 hero="Black Friday Early Access · até 50% + 22% extra",sub="11/11 · até 23h59 · cupom BLACKVIP · o público entra às 7h",
 blocos=["Hero: tela de bloqueio desbloqueada às 00:00 com a notificação \"Sua Black começou\"",
  "Caixa \"24 horas · 24 produtos · 22% extra\" + cupom BLACKVIP",
  "\"Até as 7h, só a lista\": estoque cheio, sem concorrência",
  "\"É simples\": escolha · carrinho · cupom · pronto",
  "Os 24 produtos (ou 4 + \"ver os 24\")",
  "\"Por que não deixar para depois\": os 24 esgotam · 50% + 22% · bônus dos 100 · frete prioritário · só hoje"],
 cta="USAR O CUPOM AGORA",urgencia="Só a lista até as 7h.",
 hero_tipo="Tela de bloqueio desbloqueada",hv="celular com o cadeado aberto, hora 00:00 e a notificação \"Sua Black começou\"",
 est="Hero de desbloqueio → caixa 24h/24 produtos/22% → vantagem até 7h → é simples → os 24 → 5 motivos → garantias",
 ideia="A promessa do [Fundador] cumprida à meia-noite, só para os mais engajados e para quem confirmou a vaga. É o envio de menor volume e maior engajamento do dia, que ajuda a reputação antes do envio grande das 7h.",
 historia="Ato 4, clímax (1).",
 ref=["early25","esq99a"],conexao="Primeiro disparo do 11.11 de 2025 (Early Access, oferta dupla na primeira tela) com a abertura exclusiva para a lista do 9.9. Público: engajados de 30 dias, como você definiu, somados a quem confirmou a vaga (essas pessoas pediram o acesso).",
 booster=None,teste="Só dispara se o T1 do 10.10 mostrar venda nova, não só antecipada."),
dict(data="2026-11-11",hora="07:00",janela="11.11 Black Antecipada",contexto="11.11 Black Antecipada",papel="Fase 6 · Vender: envio 2 de 5, abertura para todos",
 nome="Você foi selecionado (texto do fundador)",publico={"A":"Todos os leads ativos (exceto nunca abriu em 12 meses, bounce e reclamação)","B":"E365","C":"E180"},
 oferta="Até 50% + 22% extra com o cupom 1111, até 23h59.",
 assunto="Seu cupom foi liberado ✅",assunto_en="Your coupon has been released ✅",
 assuntos3=["Conservador: Seu cupom foi liberado ✅","Equilibrado: [Nome], você foi selecionado","Ousado: Como prometido: 22% extra, só hoje"],
 pre="1111: 22% extra nos 24 mais vendidos. Só hoje.",
 hero="Texto do [Fundador]",sub="",
 blocos=["\"Bom dia, [nome].\"",
  "\"Como prometido, a Black Antecipada começou. O seu cupom **1111** dá 22% extra em cima de preços até 50% menores. Vale até 23h59 de hoje.\"",
  "\"Os 24 mais vendidos estão aqui: USAR MEU CUPOM >>>\"",
  "\"Os que sempre esgotam costumam acabar antes do almoço.\"",
  "\"[Fundador]\""],
 cta="USAR MEU CUPOM >>>",urgencia="Até 23h59.",
 hero_tipo="Texto puro",hv="e-mail só de texto assinado pelo fundador",
 est="Saudação → promessa cumprida com cupom em negrito → link → alerta de estoque → assinatura",
 ideia="O envio mais largo do dia é o mais leve: texto de pessoa, sem imagem pesada, que é o formato que mais vende às 7h e o que melhor passa pelos filtros. Disparo em duas levas: engajados de 90 dias às 07h00 e o resto às 07h20.",
 historia="Ato 4, clímax (2). O [Fundador] cumpre a promessa para todos.",
 ref=["cupom99","reabertura"],conexao="07h de 2025 (\"você foi selecionado\") no formato do 07h que mais vende em 2026: texto com cupom (1,66 nas 9 lojas; Clube Rock 1,78). Você pediu todos os leads: fica assim no nível A; no B vai para E365 e no C para E180, que é a regra de lista toda por nível da conta.",
 booster=None,canais="SMS/WhatsApp 07h05 para toda a base de SMS: \"Black Antecipada no ar: 22% extra com 1111 até 23h59.\""),
dict(data="2026-11-11",hora="11:00",janela="11.11 Black Antecipada",contexto="11.11 Black Antecipada",papel="Fase 6 · Vender: envio 3 de 5, clube VIP",
 nome="O Clube VIP e os 24 produtos",publico={"A":"E180, sem quem já comprou hoje","B":"E180, sem quem já comprou hoje","C":"E90, sem quem já comprou hoje"},
 oferta="Cupom 1111 na primeira tela + contador do bônus dos 100 primeiros.",
 assunto="⚠️ (1) resgate pendente no seu nome",assunto_en="⚠️ (1) pending reward in your name",
 assuntos3=["Conservador: Seu 22% extra ainda está aqui","Equilibrado: ⚠️ (1) resgate pendente no seu nome","Ousado: Restam [N] bônus dos 100 primeiros"],
 pre="Seu 22% extra ainda não foi usado. Vale até 23h59.",
 hero="Seu 22% extra ainda está aqui",sub="Cabeçalho com 00h, 7h e 11h marcados. Cupom 1111 na primeira tela.",
 blocos=["Hero: cartão de membro \"Clube VIP · [Nome] · lista selecionada 11.11\" com o cupom",
  "Linha do tempo do dia com as marcas",
  "\"A verdade sobre o Clube VIP\": 3 números reais da loja (clientes ativos, compras no ano, quantos receberam este acesso)",
  "\"Os mais vendidos até agora\" + contador do bônus dos 100 primeiros"],
 cta="RESGATAR AGORA",urgencia="O bônus acaba no pedido 100.",
 hero_tipo="Cartão de membro",hv="cartão de membro VIP em estilo cartão de crédito escuro, com o nome da pessoa e o cupom",
 est="Hero de cartão de membro com cupom → linha do tempo → 3 números reais → mais vendidos com contador → garantias",
 ideia="O Clube VIP de 2025 com o cupom no topo, para quem abriu algum e-mail nos últimos 6 meses e ainda não comprou.",
 historia="Ato 4, dia do evento.",
 ref=["vip25","relogio99"],conexao="Segundo disparo do 11.11 de 2025 (\"VIP Club\") com a estrutura do 11h do 9.9 (1,24 nas 9 lojas, cupom no topo). Público de 180 dias, como você definiu, tirando quem já comprou.",
 booster=None),
dict(data="2026-11-11",hora="18:00",janela="11.11 Black Antecipada",contexto="11.11 Black Antecipada",papel="Fase 7 · Fechar: envio 4 de 5, status mudou com a surpresa",
 nome="Status mudou: tem uma surpresa no seu carrinho",publico={"A":"E90 + abriu ou clicou hoje, sem quem já comprou","B":"E90, sem quem já comprou","C":"E90, sem quem já comprou"},
 oferta="Até 50% + 22% extra com 1111 + surpresa: um desconto extra que aparece no carrinho (igual para todos que receberam), até 23h59.",
 assunto="🚨 Seu status acaba de mudar",assunto_en="🚨 Your status has just changed",
 assuntos3=["Conservador: Faltam 6 horas","Equilibrado: 🚨 Seu status acaba de mudar","Ousado: Tem uma surpresa no seu carrinho"],
 pre="Faltam 6 horas. E tem uma surpresa no carrinho.",
 hero="Conversa de celular",sub="",
 blocos=["Conversa: A: \"Entrou a Black antecipada, 22% extra com 1111\" · B: \"Coloquei no carrinho e apareceu mais um desconto 😳\" · A: \"Como assim?\" · B: \"Surpresa deles. Mas é só até meia-noite\" · A: \"Indo agora!\"",
  "Foto de produto + cupom 1111 + selo \"surpresa no carrinho\"",
  "\"Estoque crítico\": 4 produtos com a barra de estoque real",
  "\"Agora ou nunca\": cupom repetido + 3 garantias"],
 cta="VER MINHA SURPRESA",urgencia="Termina às 23h59.",
 hero_tipo="Conversa",hv="conversa de celular entre dois amigos em que um descobre um desconto surpresa no carrinho",
 est="Hero de conversa → foto com cupom e selo surpresa → estoque crítico → agora ou nunca → garantias",
 ideia="O melhor e-mail do ano, com a surpresa das 18h de 2025, para quem está engajado nos últimos 90 dias e ainda não comprou.",
 historia="Ato 4, reta final do dia.",
 ref=["conversa88","balao25"],conexao="Melhor 18h da carteira (1,48 em 33 lojas; assunto com receita 2,13) com a surpresa do 18h de 2025. Público de 90 dias, como você definiu. Sem booster neste dia: o envio das 20h30 faz esse papel.",
 booster=None,canais="SMS/WhatsApp 18h05 para quem clicou hoje e não comprou."),
dict(data="2026-11-11",hora="20:30",janela="11.11 Black Antecipada",contexto="11.11 Black Antecipada",papel="Fase 7 · Fechar: envio 5 de 5, notificação do futuro",
 nome="Notificação do futuro: falta confirmar o seu pedido",publico={"A":"E30 + clicou em algum e-mail hoje, sem quem já comprou","B":"E30 + clicou em algum e-mail hoje, sem quem já comprou","C":"Clicou em algum e-mail hoje, sem quem já comprou"},
 oferta="Até 50% + 22% extra com 1111, até 23h59. Sem prorrogação.",
 assunto="[Nome], falta você confirmar esse pedido...",assunto_en="[Name], you still need to confirm your order...",
 assuntos3=["Conservador: 🚨 [ÚLTIMA CHAMADA] A Black Antecipada expira às 23h59","Equilibrado: [Nome], falta você confirmar esse pedido...","Ousado: Seu carrinho ainda está esperando"],
 pre="Disponível só até hoje às 23h59. Depois, só na Black Week.",
 hero="Notificação do futuro · Seu pedido vai estar a caminho ✓",sub="Viemos do futuro (não tão distante) avisar que você não deixou a Black Antecipada passar. O cupom 1111 sai do ar à meia-noite.",
 blocos=["Fundo branco, cara de aviso de sistema","\"O seu eu de amanhã agradece\" + resumo do pedido simulado: preço cheio, cupom 1111, total com 22% extra, \"Melhor decisão do dia ✓\"","Botão \"CONFIRMAR MEU PEDIDO\" + \"Válido até hoje, 23h59. Sem prorrogação.\"","\"Últimas horas\": 4 produtos (os mais vendidos do dia, com a barra de estoque)"],
 cta="CONFIRMAR MEU PEDIDO",urgencia="Meia-noite.",
 hero_tipo="Notificação de pedido",hv="e-mail em fundo branco com cara de confirmação de pedido: selo \"Notificação do futuro\", resumo do pedido com o cupom 1111 aplicado e o total",
 est="Hero de notificação de pedido → resumo simulado → botão e prazo → 4 produtos com estoque → garantias",
 ideia="O fechamento que mais vende na carteira, no fechamento do maior dia antes da Black, para o menor público do dia. Fundo branco e cara de sistema também ajudam a entrega no último envio.",
 historia="Ato 4, fim do dia.",
 ref=["notif"],conexao="A notificação do futuro é o melhor fora de pico da carteira (1,67 em 39 lojas, 3,61% de clique) e foi feita para o último dia de uma oferta (28/08). Substitui o 22h de 2025, que prorrogava: aqui o fechamento é real, para a lista não aprender a esperar antes da Black Week. O last call do 7.7 fica como opção conservadora de assunto.",
 booster=None,canais="SMS/WhatsApp 20h35 para quem clicou hoje e não comprou: \"Últimas horas da Black Antecipada.\""),
# ================= ATO 5: DEPOIS DO 11.11 =================
dict(data="2026-11-13",hora="10:00",janela="11.11 Black Antecipada",contexto="O que sobrou do 11.11",papel="Pós: aviso de estoque",
 nome="Lamentamos informar",publico={"A":"E90","B":"E90","C":"E30"},
 oferta="Sem cupom. Preço do 11.11 mantido só no que sobrou.",
 assunto="Lamentamos informar que...",assunto_en="We regret to inform you that...",
 pre="Estoque baixo depois do 11.11, preço ainda promocional.",
 hero="Aviso: 13 de novembro de 2026",sub="",
 blocos=["Faixa \"Ofertas ativas · sem cupom necessário\"","Caixa de aviso: \"Por causa da procura na Black Antecipada, vários produtos estão com estoque bem abaixo do normal. O preço continua, mas quando acabar, não conseguimos repor até a Black Week.\"","\"VER O ESTOQUE QUE SOBROU\"","\"Os últimos\": 4 produtos com unidades reais"],
 cta="VER O QUE SOBROU",urgencia="Até acabar.",
 hero_tipo="Aviso de sistema",hv="e-mail em fundo branco com caixa de aviso e a data",est="Faixa → caixa de aviso → botão → 4 produtos → garantias",
 ideia="O aviso de estoque que foi a melhor campanha de setembro.",historia="Ato 5. O resultado do 11.11 vira prova para a Black Week.",
 ref=["ressaca99"],conexao="Melhor campanha de setembro na Blue Wolf (14 pedidos). Só engajados.",booster=None),
dict(data="2026-11-16",hora="10:00",janela="Intervalo",contexto="Os favoritos do 11.11",papel="Pós: vitrine dos mais vendidos",
 nome="Os favoritos do 11.11",publico=E90,
 oferta="Sem cupom novo. Frete grátis até quarta, 18/11.",
 assunto="[Nome], os favoritos do 11.11 estão te esperando",assunto_en="[Name], your 11.11 favorites are waiting for you",
 pre="Só enquanto durar o estoque.",
 hero="Os mais vendidos do 11.11 · últimas unidades",sub="As peças que todo mundo quis na Black Antecipada ainda estão aqui. Não por muito tempo.",
 blocos=["Foto grande do número 1 do 11.11","\"Os campeões do 11.11\": 4 produtos","Faixa \"Frete grátis até quarta\"","Rodapé: \"Quarta o [Fundador] tem um anúncio sobre a Black.\""],
 cta="VER OS FAVORITOS",urgencia="Estoque limitado.",
 hero_tipo="Foto de produto com selo",hv="foto grande do produto mais vendido do 11.11 com o selo \"últimas unidades\"",est="Hero de produto → campeões em grade → frete → gancho para quarta → garantias",
 ideia="A vitrine dos mais vendidos uma semana depois, o pós que funciona.",historia="Ato 5. Abre o gancho para o anúncio do [Fundador].",
 ref=["favoritos77"],conexao="Favoritos do 7.7, oito dias depois: 14 pedidos, 3,19% de clique, 1,12 na amostra ampla.",booster=None),
# ================= ATO 6: BLACK WEEK =================
dict(data="2026-11-18",hora="10:00",janela="Black Week (25 a 29/11)",contexto="O [Fundador] anuncia a Black Week: 5 dias, uma oferta nova por dia",papel="Antecipação 1 de 4: convite com agenda",
 nome="Por que a Black este ano tem 5 dias",publico={"A":"E90 + compradores do 11.11","B":"E90 + compradores do 11.11","C":"E90 + compradores do 11.11"},
 oferta="Nenhuma no e-mail. Anuncia a oferta de cada dia de 25 a 29/11. Compradores do 11.11 e a lista selecionada já estão na lista VIP.",
 assunto="[Nome], seu convite para a Black Week chegou 🎟️",assunto_en="[Name], your Black Week invitation has arrived 🎟️",
 pre="No 11.11, os 24 esgotaram em [tempo]. Por isso a Black vai ser diferente.",
 hero="Black Week · 25 a 29/11 · 5 dias de ofertas",sub="No 11.11, [N] dos 24 produtos esgotaram antes das [hora]. Muita gente ficou de fora. Por isso a Black deste ano não vai ser um dia. Vão ser 5, e cada um com uma oferta que não se repete.",
 blocos=["Abertura em nome do [Fundador], curta",
  "Hero: calendário semanal do celular com 5 eventos: qua 25 · 24 horas, 24 produtos · qui 26 · por coleção e por preço · sex 27 · Black Friday · sáb 28 · monte seu kit · dom 29 · última chamada",
  "\"Bônus: frete expresso para os 50 primeiros de cada dia\"",
  "\"Você está na lista VIP\" (compradores do 11.11 e selecionados) ou \"Garantir meu acesso VIP\"",
  "\"Guarde este número: [N]\" (gancho para 20/11)"],
 cta="GARANTIR MEU ACESSO VIP",urgencia="A lista VIP fecha dia 24 às 23h59.",
 hero_tipo="Calendário da semana",hv="visão semanal de calendário do celular com 5 eventos, um por dia, cada um com o nome da oferta",
 est="Abertura do fundador → hero de calendário semanal → bônus de frete → status da lista VIP → número para lembrar → garantias",
 ideia="O resultado do 11.11 vira o motivo da Black Week: \"muita gente ficou de fora, então agora são 5 dias\".",
 historia="Ato 6, capítulo 1. O [Fundador] volta com um motivo real (o que esgotou) e abre o loop do número.",
 ref=["bwconvite25","convite77"],conexao="O anúncio da Black Week de 2025 (\"5 days of deals\", agenda por dia, bônus de frete, \"remember this number\") no formato de convite, a antecipação de maior índice de 2026.",
 booster=None),
dict(data="2026-11-20",hora="10:00",janela="Black Week (25 a 29/11)",contexto="Black Week",papel="Antecipação 2 de 4: prova e tarefa",
 nome="O número da frustração",publico=E90,
 oferta="Nenhuma. Pede uma ação: salvar os favoritos.",
 assunto="O número que você precisa lembrar: [N] 👀",assunto_en="The number you need to remember: [N] 👀",
 pre="Fecha o loop de quarta: o que esse número significa.",
 hero="[N]: o número da frustração",sub="Lembra do número que eu te pedi para guardar? Foi quantas pessoas clicaram em \"adicionar ao carrinho\" no 11.11 e viram \"esgotado\". (Número real da loja.)",
 blocos=["Hero: print de página de produto com o selo \"ESGOTADO\" e \"[N] pessoas pediram para ser avisadas\"",
  "\"Não seja um deles\" + \"Como chegamos a estes 6 produtos\"",
  "\"Os 6 que sempre esgotam\": grade 2x3",
  "\"Faça isso agora\": entre em cada produto · clique no coração · no dia 25 você acha em 2 segundos",
  "\"Confira seu pagamento\": login · cartão · endereço · compra de teste"],
 cta="SALVAR MEUS FAVORITOS",urgencia="Faltam 5 dias.",
 hero_tipo="Página de produto esgotado",hv="print de página de produto com o selo \"ESGOTADO\" e o número de pessoas que pediram aviso",
 est="Hero de esgotado → o número → como chegamos aos 6 → grade → faça isso agora → confira o pagamento → garantias",
 ideia="Fecha o loop do número com uma frustração real e dá uma tarefa.",
 historia="Ato 6, capítulo 2.",
 ref=["n1247"],conexao="O e-mail de prova e tarefa de 19/11/2025 (\"The number of frustration: 1,247\"), com a regra do estudo: o número tem de ser o real da loja.",
 booster=None),
dict(data="2026-11-22",hora="10:00",janela="Black Week (25 a 29/11)",contexto="Black Week",papel="Antecipação 3 de 4: acesso confirmado / última chance da lista",
 nome="Acesso confirmado / Última chance da lista VIP",publico={"A":"VIP + E90 (duas versões)","B":"VIP + E90 (duas versões)","C":"VIP + E90 (duas versões)"},
 oferta="VIP: entra à 00h de quarta com frete expresso grátis no dia 25. Demais: a lista fecha dia 24 às 23h59.",
 assunto="VIP: [Nome], seu acesso à Black Week está confirmado ✅ · Demais: Última chance: a lista VIP fecha em 48h",assunto_en="VIP: [Name], your Black Week access is confirmed ✅ · Others: Last chance: the VIP list closes in 48h",
 pre="VIP: sua entrada é à 00h de quarta. Demais: depois de terça, só a fila comum.",
 hero="VIP: acesso confirmado · Demais: a lista fecha em 48h",sub="",
 blocos=["Hero para os demais: tela de SMS \"[Loja]: sua vaga VIP da Black Week expira em 48h\"",
  "VIP: passe com data, hora e frete expresso grátis no dia 25",
  "Demais: \"Quem está na lista ganha: acesso antecipado · desconto exclusivo · produtos liberados antes\" contra \"Quem não entrar até terça: fila comum · o que sobrar · sem o extra\"",
  "Demais: \"Como garantir sua vaga\" em 2 passos",
  "Os dois: \"Lançamento exclusivo para VIPs\""],
 cta="VIP: MONTAR MEU CARRINHO · Demais: ENTRAR NA LISTA VIP",urgencia="A lista fecha terça às 23h59.",
 hero_tipo="SMS",hv="tela de SMS com a mensagem da loja sobre a vaga VIP expirando em 48h",
 est="Hero de SMS → versão VIP (passe) ou versão pendente (ganha x perde) → como garantir → lançamento VIP → garantias",
 ideia="A véspera vira prazo: a lista fecha.",
 historia="Ato 6, capítulo 3.",
 ref=["lastvip25"],conexao="\"Last chance: VIP list ends today\" de 23/11/2025, e o assunto de acesso confirmado (receita 1,48).",
 booster=None),
dict(data="2026-11-24",hora="10:00",janela="Black Week (25 a 29/11)",contexto="Black Week",papel="Antecipação 4 de 4: véspera com checklist",
 nome="Checklist da Black Week",publico=E90,
 oferta="Nenhuma nova.",
 assunto="Amanhã começa a Black Week. Você está pronto?",assunto_en="Black Week starts tomorrow. Are you ready?",
 pre="00h para a lista VIP, 7h para todos. O primeiro dia tem só 24 produtos.",
 hero="Amanhã: 24 horas, 24 produtos",sub="O primeiro dia da Black Week tem a oferta mais curta da semana. Quem se preparar leva.",
 blocos=["Hero: app de notas com \"Black Week\" e o checklist: alarme · endereço · favoritos salvos · cartão salvo","Agenda dos 5 dias em linha","\"Já no preço\": 4 produtos","\"Te vejo à meia-noite\""],
 cta="VER O QUE JÁ ESTÁ NO PREÇO",urgencia="Amanhã às 00h (VIP) e 7h (todos).",
 hero_tipo="Checklist no app de notas",hv="print do app de notas com o título \"Black Week\" e 4 itens com caixa de seleção",
 est="Hero de notas → agenda dos 5 dias → já no preço → despedida → garantias",
 ideia="A véspera com checklist, a que vende.",historia="Ato 6, capítulo 4.",
 ref=["check25","vespera88"],conexao="Mesma véspera com checklist do 10.10 e do 11.11, a versão de véspera que vendeu no 8.8 e em 2025.",booster=None,
 canais="SMS/WhatsApp 18h: \"Amanhã começa a Black Week. 24 produtos só no primeiro dia.\""),
]
