E90={"A":"E90","B":"E90","C":"E90"}
P18={"A":"E180","B":"E180","C":"E90"}
VOT={"A":"VOTOU-1010","B":"VOTOU-1010","C":"VOTOU-1010"}
OUT=[
# ================= ATO 1: A GERENTE E OS NOTA 10 =================
dict(data="2026-10-01",hora="10:00",janela="Outubro Pré-Black",contexto="Outubro começa com um jogo: só um de 8 cupons funciona",papel="Abertura do mês: gamificada com o desconto revelado no checkout",
 nome="Quer jogar um jogo?",publico=E90,
 oferta="Um dos 8 cupons do e-mail dá 10% em todo o site; os outros 7 não fazem nada. Até domingo, 04/10, às 23h59.",
 assunto="Quer jogar um jogo? Só um destes cupons funciona 🔑",assunto_en="Want to play a game? Only one of these codes works 🔑",
 assuntos3=["Conservador: (1) cupom escondido para [nome] neste e-mail 🤫","Equilibrado: Quer jogar um jogo? Só um destes cupons funciona 🔑","Ousado: Adivinha qual é o cupom de outubro"],
 pre="8 cupons, 1 funciona. Você descobre no checkout.",
 hero="Quer jogar um jogo?",sub="Um destes 8 cupons dá 10% em todo o site. Os outros 7 não fazem nada. Escolha um produto, vá até o checkout e teste o seu palpite. Só até domingo.",
 blocos=["Assinatura no topo: \"[Gerente], gerente de relacionamento da [Loja]\" (é ela quem conduz outubro)",
  "Hero: \"QUER JOGAR UM JOGO?\" + \"Um destes cupons desbloqueia 10% em todo o site\" + grade de 8 botões com os códigos (ex.: OUTUBRO · SORTE · CHAVE · ACERTO · PALPITE · JOGADA · BINGO · ACHEI)",
  "\"Você tem um palpite. Testa no checkout.\" + botão único \"TESTAR MINHA SORTE\"",
  "\"Onde testar\": grade 2x2 com os mais vendidos, cada um com \"aplique seu palpite no checkout\"",
  "Regra curta (da sexta premiada): \"Aplique o cupom no checkout para descobrir se é o certo. Válido até domingo às 23h59.\"",
  "P.S. da [Gerente]: \"Domingo chega outro e-mail meu. É um convite, e tem a ver com o dia 10.\""],
 cta="TESTAR MINHA SORTE",urgencia="Até domingo, 04/10, às 23h59.",
 hero_tipo="Jogo de códigos",hv="hero escuro com o título \"Quer jogar um jogo?\" e uma grade de 8 botões com nomes de cupom, como a peça \"What's The Discount Code\" da Well Copy, com um botão único abaixo",
 est="Assinatura da gerente → hero com a grade de 8 cupons → instrução curta e botão único → grade 2x2 onde testar → regra do checkout e prazo → P.S. que abre o gancho do dia 10 → garantias",
 ideia="O \"What's The Discount Code\" da Well Copy: a pessoa escolhe um produto e vai ao checkout para testar o palpite, e no checkout ela está a um clique da compra. É a mesma mecânica de desconto revelado no checkout que mais vende na carteira fora dos picos.",
 historia="Ato 1, capítulo 1. Apresenta a [Gerente] com um jogo e deixa o gancho: \"domingo chega um convite, tem a ver com o dia 10\".",
 ref=["wc_code","sexta"],conexao="Das 29 campanhas da Well Copy, é a que o próprio cartão descreve com o engajamento mais alto (\"REALLY high engagement\") e a que leva a pessoa direto ao checkout. A mecânica por baixo é a da sexta premiada (\"aplique o cupom no checkout para descobrir seu desconto\": 1,22 nas 9 lojas, 9 pedidos), da Segunda turbo (maior ticket de agosto) e do Revele (18 pedidos, recorde do trimestre). O desconto é pequeno (10%) e acaba no domingo, para não competir com o 10.10.",
 booster=None,evid="validado (mecânica) + inspiração (Well Copy)"),
dict(data="2026-10-02",hora="10:00",janela="Preparação",contexto="Limpeza de lista antes da Black",papel="Reativação (complemento)",
 nome="Reativação 1",publico={"A":"Inativos 180 a 365 dias","B":"Inativos 180 a 365 dias","C":"Compradores antigos em lote"},
 oferta="Nenhuma. Botão \"Quero continuar recebendo\" grava a tag de reativado.",
 assunto="[Nome], posso continuar te avisando?",assunto_en="[Name], can I keep letting you know?",
 pre="Nos próximos dois meses vêm as melhores ofertas do ano.",
 hero="Texto da gerente, sem imagem",sub="",
 blocos=["\"Oi, [nome]. Aqui é a [Gerente], gerente de relacionamento da [Loja].\"",
  "\"Faz um tempo que você não abre nossos e-mails, e tudo bem. Só que os próximos dois meses são os melhores do ano por aqui, e eu não queria que você ficasse de fora sem saber.\"",
  "\"Quer continuar recebendo? É só clicar aqui: QUERO CONTINUAR >>>\"",
  "\"Se não quiser, tudo bem. Você para de receber sem precisar fazer nada.\" Assinatura."],
 cta="QUERO CONTINUAR >>>",urgencia="",
 hero_tipo="Texto puro",hv="e-mail só de texto, fundo branco, assinado pela gerente",
 est="Texto da gerente → pergunta direta → link em caixa alta → assinatura",
 ideia="Pergunta direta a quem sumiu, na voz da mesma personagem de outubro.",
 historia="Fora da história principal: vai só para inativos.",
 ref=["reabertura"],conexao="Limpa a lista antes do volume de novembro (plano do Max). Formato de texto assinado da reabertura de 25/07 (1,15 na amostra ampla). Na Brinque Mais, a lista limpa abriu 25% contra 14%.",
 booster=None,evid="complemento"),
dict(data="2026-10-04",hora="10:00",janela="10.10 Nota 10",contexto="10.10 Nota 10 (Brasil) · Perfect 10 Sale (global): os nota 10 com o maior desconto antes da Black",papel="Antecipação 1 de 4: convite",
 nome="Seu convite para o 10.10 Nota 10",publico=E90,
 oferta="No e-mail: ofertas de esquenta já ativas no site. No dia 10: até 40% no site + 20% extra com o cupom 1010.",
 assunto="[Nome], seu convite para o 10.10 chegou 🎟️",assunto_en="[Name], your 10.10 invitation has arrived 🎟️",
 pre="Os nota 10 vão ter o maior desconto antes da Black. E você vai ajudar a escolher.",
 hero="Você está convidado · 10.10 Nota 10",sub="Dez é a nota máxima. No dia 10/10, os produtos que os nossos clientes avaliaram com nota 10 entram com o maior desconto que damos antes da Black. E um deles vai ficar ainda mais barato: quem escolhe são vocês.",
 blocos=["Hero: convite de calendário do celular. \"10.10 Nota 10 · sábado, 10 de outubro · 00h às 23h59 · Organizadora: [Gerente], [Loja]\" com \"Aceitar · Talvez · Recusar\"",
  "\"Os 4 momentos do dia\": 00h (quem votar) · 07h (cupom para todos) · 11h (brinde dos 100 primeiros) · 18h (última chamada)",
  "\"Na terça você vota\": dos 4 nota 10, o mais votado entra com o maior desconto do dia",
  "\"Já em oferta no esquenta\": grade 2x2 com produtos que já estão com preço reduzido hoje",
  "Barra de status: convite enviado › lido › aceito",
  "Botão \"ACEITAR O CONVITE\""],
 cta="ACEITAR O CONVITE",urgencia="A votação abre terça.",
 hero_tipo="Convite de calendário",hv="tela de celular com um convite de evento do calendário, título \"10.10 Nota 10\", data, horário, organizadora e os botões Aceitar, Talvez e Recusar",
 est="Hero de convite de calendário → os 4 momentos do dia → anúncio da votação → esquenta ativo em grade 2x2 → barra de status → botão → garantias",
 ideia="O convite do 7.7 com cara de convite de calendário. Fecha o loop do dia 01 (o que acontece com os nota 10) e abre o próximo (a votação).",
 historia="Ato 1, capítulo 2. Cumpre o P.S. do dia 01 (o convite chegou), apresenta os nota 10 e abre o loop da votação.",
 ref=["convite77","cal99"],conexao="Convite com confirmação é a antecipação de maior índice das duas amostras (7.7: 1,55; 6.6: 1,63). O esquenta do 9.9 (05/09) trouxe a seção \"already on sale: warm-up deals\", que fez a antecipação vender sem cupom (12 pedidos, o melhor esquenta do 9.9).",
 booster=None),
dict(data="2026-10-06",hora="10:00",janela="10.10 Nota 10",contexto="10.10 Nota 10 · Perfect 10 Sale",papel="Antecipação 2 de 4: votação e agenda",
 nome="Qual dos nota 10 fica mais barato?",publico=E90,
 oferta="Votação: o mais votado dos 4 entra no dia 10 com o maior desconto da loja. Quem votar entra às 00h. Esquenta ativo.",
 assunto="[Nome], você já viu o que está vindo? 👀",assunto_en="[Name], have you seen what is coming? 👀",
 pre="A votação abriu. Quem vota entra antes de todo mundo.",
 hero="Você escolhe qual fica mais barato",sub="No domingo te convidei. Hoje, como prometido, a agenda completa e a votação. O mais votado até quinta entra no dia 10 com o maior desconto do dia.",
 blocos=["Hero: enquete de story do Instagram com os 4 nota 10 e a parcial em barras",
  "4 cartões de produto com nota média e uma frase real de avaliação; botão \"VOTAR NESTE\" em cada um",
  "\"Quem vota entra às 00h\": o site abre primeiro para quem votou, com estoque cheio",
  "\"Como vai funcionar o 10.10\": 00h abertura (quem votou) · 07h cupom liberado · 11h destaques e brinde · 18h última chamada",
  "FAQ: Preciso de cadastro especial? (não) · Vale para o site todo? · E se eu não conseguir às 7h? (tem 11h e 18h, mas alguns produtos podem acabar) · Vai ter prorrogação? (não)",
  "\"Já em oferta no esquenta\": 4 produtos"],
 cta="VOTAR",urgencia="Votação até quinta, 08/10, às 23h59.",
 hero_tipo="Enquete de story",hv="tela de story do Instagram com um sticker de enquete de 4 opções e as barras de porcentagem",
 est="Hero de enquete → 4 cartões de voto → regra do 00h → como vai funcionar → FAQ → esquenta ativo → garantias",
 ideia="A antecipação ganha uma tarefa. Cada voto é um clique que vira segmento e dá entrada às 00h.",
 historia="Ato 1, capítulo 3. A votação é o motivo novo para abrir; o assunto é o da agenda do 7.7.",
 ref=["agenda77","esq88b"],conexao="A agenda do 7.7 teve a maior abertura de 2026 (44,3%) e vendeu mais que o 07h do dia; o assunto tem receita 1,77 (5 de 5). O \"como vai funcionar\" e o FAQ são os do 05/08 e do 08/09, com a copy real da versão Brasil.",
 booster=None,evid="validado + mecânica nova (votação)"),
dict(data="2026-10-08",hora="10:00",janela="10.10 Nota 10",contexto="10.10 Nota 10 · Perfect 10 Sale",papel="Antecipação 3 de 4: parcial da votação e acesso",
 nome="A votação está apertada",publico={"A":"Duas versões: VOTOU-1010 · demais E90","B":"Duas versões: VOTOU-1010 · demais E90","C":"Duas versões: VOTOU-1010 · demais E90"},
 oferta="Revela o bônus: os 100 primeiros pedidos do dia 10 levam [BRINDE]. Quem votou entra às 00h com frete grátis.",
 assunto="Votou: [Nome], seu acesso está confirmado ✅ · Não votou: ⚠️ [Nome], seu voto ainda não foi computado",assunto_en="Voted: [Name], your access is confirmed ✅ · Didn't vote: ⚠️ [Name], your vote hasn't been counted yet",
 pre="A diferença entre os dois primeiros é de [X] votos.",
 hero="Mensagem da [Gerente]",sub="",
 blocos=["Hero: conversa de iMessage da [Gerente]: \"[Nome], a votação tá apertada\" · \"[Produto A] 41% x [Produto B] 38%\" · \"Quem votou entra meia-noite, com frete grátis\" · resposta: \"Já votei 👀\" · \"Então te vejo às 00h\"",
  "Quem votou: passe com a data, 00h, cupom exclusivo por e-mail e o bônus revelado (brinde dos 100 primeiros)",
  "Quem não votou: caixa de aviso em fundo branco \"Pendência: seu voto ainda não foi computado\" com os 4 botões",
  "\"Como garantir\" em 3 passos: escolha e deixe no carrinho · sexta às 23h55 esteja on-line · finalize assim que o cupom chegar",
  "\"Já em oferta no esquenta\": 4 produtos"],
 cta="Votou: MONTAR MEU CARRINHO · Não votou: VOTAR AGORA",urgencia="A votação fecha hoje às 23h59.",
 hero_tipo="Conversa de iMessage",hv="conversa de iMessage com balões cinza da gerente e azuis do cliente, mostrando o placar parcial",
 est="Hero de conversa → passe de acesso ou aviso de pendência → bônus dos 100 → como garantir em 3 passos → esquenta ativo → garantias",
 ideia="A parcial é a notícia nova, contada pela própria personagem em uma conversa, o hero do melhor e-mail do ano.",
 historia="Ato 1, capítulo 4. Aumenta a tensão (placar apertado) e separa quem participou de quem não participou.",
 ref=["esq99a","bonus25"],conexao="O 07/09 do 9.9 trouxe a abertura exclusiva para a lista (\"quatro horas de vantagem antes do público\"). O bônus dos 100 primeiros revelado antes do dia vem de 08/11/2025. Assunto de acesso confirmado: receita 1,48 (3 de 3); pendência: 1,52.",
 booster=None),
dict(data="2026-10-09",hora="10:00",janela="10.10 Nota 10",contexto="10.10 Nota 10 · Perfect 10 Sale",papel="Antecipação 4 de 4: resultado e checklist",
 nome="Resultado da votação + checklist",publico=E90,
 oferta="Revela o vencedor e o desconto dele. Esquenta ativo.",
 assunto="Amanhã é 10.10. Você está pronto?",assunto_en="Tomorrow is 10.10. Are you ready?",
 pre="O vencedor da votação entra com [X]% à meia-noite.",
 hero="Deu [produto]",sub="O [produto] venceu com [X]% dos votos e entra amanhã com [desconto]. Quem votou entra à meia-noite. Todo mundo, às 7h.",
 blocos=["Hero: tela de bloqueio com a notificação \"[Loja] · Resultado da votação: [produto] venceu. Entra com [X]% à 00h.\"",
  "Foto grande do vencedor com a nota média e o selo \"Nota 10 escolhido por vocês\"",
  "\"Pronto para amanhã?\" (copy real do 8.8): ☐ Anotou os horários? · ☐ Colocou o alarme às 23h55 (quem votou) ou 6h55? · ☐ Já escolheu? · ☐ Já passou no site para ver o esquenta?",
  "\"Faltou algum? Ainda dá tempo. O esquenta está rodando agora.\"",
  "Bilhete \"Hoje 09/10 → Amanhã 10/10 · primeira leva à 00h\""],
 cta="PREPARAR MEU CARRINHO",urgencia="Amanhã, das 00h às 23h59.",
 hero_tipo="Notificação na tela de bloqueio",hv="celular na tela de bloqueio com a notificação da loja anunciando o vencedor",
 est="Hero de notificação → vencedor com nota → checklist de 4 itens → esquenta ativo → bilhete hoje/amanhã → garantias",
 ideia="Fecha o loop da votação e transforma a espera em tarefa.",
 historia="Ato 1, capítulo 5. Fecha o loop aberto no dia 04 e prepara o dia.",
 ref=["vespera88","check25"],conexao="A véspera com checklist foi o melhor esquenta do 8.8 (10 pedidos) e é a véspera de 10/11/2025. Copy real da versão Brasil (\"Quem chega antes leva o melhor\").",
 booster=None,canais="SMS/WhatsApp 18h: \"Resultado da votação: [produto] venceu. Amanhã à meia-noite.\""),
dict(data="2026-10-10",hora="00:00",janela="10.10 Nota 10",contexto="10.10 Nota 10 · Perfect 10 Sale",papel="Pico: abertura antecipada para quem votou",
 nome="Liberado para você",publico=VOT,
 oferta="Até 40% no site + 20% extra com o cupom 1010 + o vencedor com [desconto] + frete grátis, das 00h às 7h só para quem votou.",
 assunto="🔓 Seu acesso antecipado foi liberado",assunto_en="🔓 Your early access is live",
 pre="Você votou. O site abriu só para você até as 7h.",
 hero="Acesso liberado",sub="É meia-noite e o 10.10 abriu só para quem votou. Até as 7h: estoque cheio, sem concorrência, com frete grátis.",
 blocos=["Hero: celular com o cadeado aberto e a notificação \"[Loja] · 10.10 liberado para você · agora\"",
  "Cupom 1010 + \"até 40% + 20% extra\" + selo \"frete grátis até 7h\"",
  "O vencedor da votação em destaque com o preço do dia",
  "\"Os nota 10\": grade com os mais bem avaliados",
  "\"É simples\": escolha · carrinho · cupom 1010 · frete aplicado"],
 cta="ENTRAR ANTES DE TODO MUNDO",urgencia="Frete grátis até 7h.",
 hero_tipo="Tela de bloqueio desbloqueada",hv="celular com o cadeado aberto, hora 00:00 e a notificação \"10.10 liberado para você\"",
 est="Hero de desbloqueio → cupom e benefício → vencedor → grade dos nota 10 → é simples → garantias",
 ideia="Quem cumpriu a tarefa (votar) recebe o que foi prometido, na hora prometida.",
 historia="Ato 1, clímax. Cumpre a promessa do dia 06.",
 ref=["early25","esq99a"],conexao="Abertura do 11.11 de 2025 (\"Early Access\", oferta dupla na primeira tela) e a abertura exclusiva do 9.9. O benefício é frete grátis, não desconto maior, para não furar a escada do 11.11.",
 booster=None,teste="T1: quem votou recebe às 00h. Comparar pedidos das 00h às 23h59 com quem abriu a votação e não votou (recebe às 7h)."),
dict(data="2026-10-10",hora="07:00",janela="10.10 Nota 10",contexto="10.10 Nota 10 · Perfect 10 Sale",papel="Pico: disparo 1",
 nome="Cupom liberado (texto da gerente)",publico=E90,
 oferta="Até 40% no site + 20% extra com o cupom 1010, até 23h59. O vencedor com [desconto]. Os 100 primeiros ganham [BRINDE].",
 assunto="Seu cupom foi liberado ✅",assunto_en="Your coupon has been released ✅",
 pre="1010: 20% extra em cima de preços até 40% menores. Só hoje.",
 hero="Texto puro assinado pela [Gerente]",sub="",
 blocos=["\"Oi, [nome]. O 10.10 começou.\"",
  "\"O seu cupom **1010** dá 20% extra em cima de preços que já estão até 40% menores. Vale até 23h59 de hoje.\"",
  "\"O [produto] ganhou a votação e está com [desconto]. É o menor preço que ele vai ter antes da Black.\"",
  "\"USAR MEU CUPOM >>>\"",
  "\"P.S. Os 100 primeiros pedidos levam [BRINDE]. Quando eu escrevi este e-mail, restavam [N].\""],
 cta="USAR MEU CUPOM >>>",urgencia="Até 23h59 de hoje.",
 hero_tipo="Texto puro",hv="e-mail só de texto, assinado pela gerente",
 est="Texto → cupom em negrito → vencedor da votação → link em caixa alta → P.S. com contador",
 ideia="O 07h que mais vende na carteira é texto de pessoa.",
 historia="Ato 1, dia do evento. A [Gerente] abre o dia para todos.",
 ref=["cupom99","reabertura"],conexao="07h em texto: 1,66 nas 9 lojas e o disparo de maior índice da Clube Rock (1,78). Formato de texto assinado da reabertura de 25/07.",
 booster=None,canais="SMS/WhatsApp 07h05: \"10.10 no ar: 20% extra com 1010 até 23h59. [link]\""),
dict(data="2026-10-10",hora="11:00",janela="10.10 Nota 10",contexto="10.10 Nota 10 · Perfect 10 Sale",papel="Pico: disparo 2",
 nome="Cada hora do 10.10",publico=E90,
 oferta="Cupom 1010 na primeira tela + contador real do brinde dos 100 primeiros.",
 assunto="⚠️ (1) brinde reservado no seu nome",assunto_en="⚠️ (1) gift reserved in your name",
 pre="Restam [N] brindes. O cupom 1010 continua até 23h59.",
 hero="Cada hora do 10.10",sub="\"O 10.10 está no ar. Do primeiro café até a última luz apagada.\" Cupom 1010 e o contador de brindes na primeira tela.",
 blocos=["Cabeçalho com 00h, 7h e 11h marcados + cupom 1010 + \"restam [N] brindes\"",
  "Relógio e linha do tempo (copy real do 9.9): 07:00 portas abertas · 09:00 primeiros pedidos confirmados · 11:00 brinde no ar · 12:00 pausa pro almoço, não pro cupom · 18:00 última chamada com estoque cheio · 21:00 os mais buscados estão sumindo · 23:00 cupom nos últimos minutos · 00:00 encerrado",
  "\"Em oferta agora\": 4 produtos",
  "\"A condição vale o dia inteiro, mas o estoque não espera.\""],
 cta="GARANTIR O MEU",urgencia="O brinde acaba no pedido 100. O cupom, às 23h59.",
 hero_tipo="Relógio e linha do tempo",hv="cabeçalho com os horários do dia marcados, cupom em caixa e um relógio com a linha do tempo do dia",
 est="Cabeçalho de horários com cupom e contador → relógio com linha do tempo → 4 produtos → frase de fechamento → garantias (com metade da altura do original)",
 ideia="Mostra onde o dia está e quanto falta, com a oferta no topo.",
 historia="Ato 1, dia do evento.",
 ref=["relogio99","cem88"],conexao="11h do 9.9: 1,24 nas 9 lojas e 2,70% de clique, com o cupom no topo. Os 100 primeiros do 8.8. O original tem 4.136 px: cortar pela metade.",
 booster=None),
dict(data="2026-10-10",hora="18:00",janela="10.10 Nota 10",contexto="10.10 Nota 10 · Perfect 10 Sale",papel="Pico: disparo 3 (principal do dia)",
 nome="Status mudou (conversa)",publico=P18,
 oferta="Até 40% no site + 20% extra com o cupom 1010, até 23h59.",
 assunto="🚨 Seu status acaba de mudar",assunto_en="🚨 Your status has just changed",
 pre="Abra e veja o que eu separei para você.",
 hero="Conversa de celular",sub="",
 blocos=["Conversa (copy real do 8.8, adaptada): Rafa: \"Corre no site da [Loja]. 20% extra em tudo hoje com o cupom 1010.\" · \"Peguei o que ganhou a votação. Metade das coisas que eu tava de olho já esgotou.\" · Léo: \"Sério? Ainda tem coisa boa?\" · Rafa: \"Tem sim! Mas tá saindo rápido... e vai só até meia-noite.\" · Léo: \"Tô indo agora!!\"",
  "Foto do produto em uso + cupom 1010",
  "\"Ainda dá tempo de garantir esses\": 4 produtos",
  "\"É agora ou nunca\": \"O 10.10 acaba à meia-noite.\" + cupom repetido + 3 garantias"],
 cta="GARANTIR ANTES DA MEIA-NOITE",urgencia="Termina às 23h59.",
 hero_tipo="Conversa",hv="conversa de celular entre dois amigos, com o cupom citado e foto de produto logo abaixo",
 est="Hero de conversa → foto com cupom → 4 produtos → agora ou nunca → garantias",
 ideia="O e-mail que mais vendeu no ano, reservado para o disparo principal do pico.",
 historia="Ato 1, fechamento do dia.",
 ref=["conversa88"],conexao="Melhor e-mail de 2026: 18 pedidos e US$ 107,5 por mil na Blue Wolf, 1,48 em 33 lojas, assunto com receita 2,13 (5 de 5).",
 booster=dict(quando="21h30 (delay de 3h30)",para="nonOpeners",assunto="🚨 [ÚLTIMA CHAMADA] O 10.10 expira às 23h59"),
 canais="SMS/WhatsApp 20h30 para quem clicou e não comprou: \"Últimas horas do 10.10.\""),
dict(data="2026-10-12",hora="10:00",janela="10.10 Nota 10",contexto="O que sobrou do 10.10",papel="Pós: aviso de estoque",
 nome="Lamentamos informar",publico={"A":"E90","B":"E90","C":"E30"},
 oferta="Sem cupom. Preço do 10.10 mantido só no que sobrou, até acabar.",
 assunto="Lamentamos informar que...",assunto_en="We regret to inform you that...",
 pre="Estoque baixo, mas ainda com o preço do 10.10.",
 hero="Aviso: 12 de outubro de 2026",sub="",
 blocos=["Faixa \"Ofertas ativas · sem cupom necessário\"",
  "Caixa de aviso: \"Por causa da procura no 10.10, vários produtos estão com estoque bem abaixo do normal. O preço promocional continua no site, mas quando o estoque atual acabar, não conseguimos manter.\"",
  "Botão \"VER O ESTOQUE QUE SOBROU\"",
  "\"Aproveite as últimas unidades\": 4 produtos com o número real de unidades"],
 cta="VER O QUE SOBROU",urgencia="Até o estoque acabar.",
 hero_tipo="Aviso de sistema",hv="e-mail em fundo branco com caixa de aviso com ícone de alerta e a data",
 est="Faixa de ofertas ativas → caixa de aviso → botão → 4 produtos com unidades → garantias",
 ideia="Depois do pico, um aviso que parece mensagem de sistema, não campanha.",
 historia="Ato 1, epílogo.",
 ref=["ressaca99"],conexao="Melhor campanha de setembro na Blue Wolf (14 pedidos, US$ 77,7 por mil), o dobro da ressaca \"Missed our 8.8?\". Copy real da versão Brasil.",
 booster=None),
dict(data="2026-10-13",hora="10:00",janela="Preparação",contexto="Limpeza de lista",papel="Reativação 2 (complemento)",
 nome="Reativação 2",publico={"A":"Não abriu a reativação 1","B":"Não abriu a reativação 1","C":"Não abriu a reativação 1"},
 oferta="Nenhuma.",assunto="Última pergunta antes da Black, [nome]",assunto_en="One last question before Black Friday, [name]",
 pre="Se não quiser mais, tudo bem.",hero="Texto da gerente",sub="",
 blocos=["\"Oi, [nome]. Mandei um e-mail há dez dias e não sei se chegou.\"","\"Novembro vai ser o mês mais movimentado do ano por aqui. Quer receber?\"","\"QUERO CONTINUAR >>>\". Quem não clicar sai da lista de envio da Black."],
 cta="QUERO CONTINUAR >>>",urgencia="",hero_tipo="Texto puro",hv="e-mail só de texto",est="Texto curto → link → assinatura",ideia="Última tentativa antes de suprimir.",historia="Fora da história principal.",
 ref=["reabertura"],conexao="Protege a entregabilidade de novembro.",booster=None,evid="complemento"),
# ================= ATO 2: LISTA DE ESPERA E PRÉ-BLACK =================
dict(data="2026-10-15",hora="10:00",janela="Outubro Pré-Black",contexto="Lista de espera da Black",papel="Captação (Max, outubro)",
 nome="A lista de espera da Black abriu",publico=E90,
 oferta="Nenhuma. Quem entra na lista de espera recebe o aviso da Black antes e entra no sorteio das vagas da lista selecionada do 11.11 (quem responder ou deixar o telefone).",
 assunto="[Nome], te mandei um áudio 🎧",assunto_en="[Name], I sent you a voice note 🎧",
 pre="47 segundos sobre a Black, e por que ter o seu nome na lista muda tudo.",
 hero="Áudio da [Gerente]",sub="",
 blocos=["Hero: conversa de WhatsApp com a foto da [Gerente] e uma mensagem de voz de 0:47",
  "Transcrição: \"Oi, [nome]. Aqui é a [Gerente]. Todo ano o mesmo filme: a Black chega, o site lota e os produtos que vocês mais pedem acabam no primeiro dia. Esse ano eu abri uma lista de espera. Quem estiver nela fica sabendo de tudo antes. É de graça, é só clicar no botão.\"",
  "\"O que a lista de espera te dá\": ✓ aviso antes de todo mundo · ✓ prioridade na lista selecionada do 11.11 · ✓ frete prioritário na Black Week",
  "Botão \"ENTRAR NA LISTA DE ESPERA\" (grava ESPERA-BLACK) + pop-up com e-mail e telefone no site",
  "P.S. \"Responde este e-mail com o produto que você está esperando. Eu leio todos.\""],
 cta="ENTRAR NA LISTA DE ESPERA",urgencia="",
 hero_tipo="Áudio de WhatsApp",hv="conversa de WhatsApp com a foto de perfil da gerente e um balão de mensagem de voz com a onda sonora e a duração 0:47",
 est="Hero de áudio → transcrição → benefícios da lista → botão → P.S. pedindo resposta",
 ideia="A [Gerente] planta a lista que o [Fundador] vai transformar em lista selecionada em 02/11. O pedido de resposta melhora a reputação do remetente antes do pico.",
 historia="Ato 2, capítulo 1. Abre o loop da Black e planta a lista.",
 ref=["lastvip25","wc_voice"],conexao="Ficha de outubro do Max (captação com a isca de acesso antecipado). O conteúdo é o da lista VIP de 2025 (23/11: quem entra ganha, quem não entra perde). O formato é o \"Voice Note From The Founder\" da Well Copy, que anunciava justamente o acesso antecipado da Black. O pedido de resposta é o bloco 6 do e-mail de desejo de 2025.",
 booster=None,evid="validado (conteúdo) + inspiração (formato)",canais="Pop-up de lista de espera no site com e-mail e telefone, de 15/10 a 01/11."),
dict(data="2026-10-19",hora="10:00",janela="Semana Pré-Black (19 a 24/10)",contexto="Semana Pré-Black: a [Gerente] conseguiu liberar uma prévia do preço da Black",papel="Semana de oferta: abertura",
 nome="Preço cheio: OFF · Pré-Black: ON",publico=E90,
 oferta="Até 30% no site + 15% extra com o cupom PREBLACK15, de segunda a sexta, 23/10, às 23h59.",
 assunto="Ativei a Pré-Black para você ✅",assunto_en="I've activated Pre-Black Friday for you ✅",
 pre="Até 30% + 15% extra, de hoje até sexta.",
 hero="Preço cheio: OFF · Pré-Black: ON",sub="Algumas semanas pedem uma condição melhor. Essa é uma delas. Eu consegui liberar uma prévia do preço da Black, só até sexta.",
 blocos=["Hero: interruptores de configuração do celular: \"PREÇO CHEIO: OFF\" e \"PRÉ-BLACK: ON\"",
  "Cupom PREBLACK15 + \"Válido até sexta, 23h59\" + botão \"ATIVAR MEUS 15%\"",
  "\"Desconto não muda o que você queria comprar. Muda o momento de comprar. Aquilo que você deixou para depois custa menos até sexta. Depois volta ao normal.\"",
  "\"Os fáceis de escolher\": 4 produtos",
  "Assinatura curta: \"[Gerente]\" + interruptor repetido no fim"],
 cta="ATIVAR MEUS 15%",urgencia="Até sexta às 23h59.",
 hero_tipo="Interruptor de configuração",hv="tela de ajustes do celular com \"Preço cheio\" desligado e \"Pré-Black\" ligado em verde",
 est="Hero de interruptores → cupom e validade → texto curto → 4 produtos → assinatura → interruptor repetido → garantias",
 ideia="A [Gerente] é a personagem generosa: libera uma prévia da Black.",
 historia="Ato 2, capítulo 2. A [Gerente] abre a semana de oferta dela.",
 ref=["onoff"],conexao="A semana de oferta da carteira abriu com o On & Off: 2,89% de clique, o melhor dos três. Copy real da versão Brasil. A oferta repete o formato da Mid-Year Black (até X% + extra), a semana que mais vendeu em 2026.",
 booster=None),
dict(data="2026-10-21",hora="10:00",janela="Semana Pré-Black (19 a 24/10)",contexto="Semana Pré-Black",papel="Semana de oferta: meio",
 nome="Notícia de última hora: 48h para o fim da Pré-Black",publico=E90,
 oferta="Até 30% + 15% extra com PREBLACK15, até sexta às 23h59.",
 assunto="[Nome], chegou a notícia que você não queria...",assunto_en="[Name], the news you did not want to hear has arrived...",
 pre="A Pré-Black termina sexta às 23h59.",
 hero="Notícia de última hora · 48h até o fim da Pré-Black",sub="Quarta, 21 de outubro de 2026. A campanha encerra sexta às 23h59. Até 30% no site + 15% extra com o cupom PREBLACK15.",
 blocos=["Cabeçalho de jornal com a data e a manchete","Cupom PREBLACK15 em caixa + \"COMPRAR AGORA\"","Foto da embalagem ou do produto principal","\"Os destaques da manchete\": 4 produtos"],
 cta="COMPRAR AGORA",urgencia="48 horas.",
 hero_tipo="Jornal",hv="primeira página de jornal com a data do dia, a manchete \"48h até o fim da Pré-Black\" e o cupom em caixa",
 est="Cabeçalho de jornal → cupom → foto → destaques da manchete → garantias",
 ideia="O jornal foi feito para o meio de uma semana de oferta: 48 horas para o fim.",
 historia="Ato 2, capítulo 3.",
 ref=["jornal22","jornal99"],conexao="O jornal de 22/07 era exatamente \"48h para o fim da Mid-Year Black\": 15 pedidos, 1,62 nas 9 lojas, 1,10 na amostra ampla. Copy real da versão Brasil do 9.9 (\"Notícia de última hora\").",
 booster=None),
dict(data="2026-10-23",hora="10:00",janela="Semana Pré-Black (19 a 24/10)",contexto="Semana Pré-Black",papel="Semana de oferta: fechamento",
 nome="Notificação do futuro",publico=E90,
 oferta="Último dia do PREBLACK15: até 30% + 15% extra, até 23h59.",
 assunto="[Nome], falta você confirmar esse pedido...",assunto_en="[Name], you still need to confirm your order...",
 pre="Disponível só até hoje às 23h59.",
 hero="Notificação do futuro · Seu pedido vai estar a caminho ✓",sub="Viemos do futuro (não tão distante) avisar que você não deixou essa oferta passar. É o último dia do seu cupom da Pré-Black.",
 blocos=["Fundo branco, cara de aviso de sistema","\"O seu eu de amanhã agradece\" + resumo do pedido simulado com o cupom PREBLACK15 e \"Melhor decisão do dia ✓\"","Botão \"APROVEITAR DESCONTO\" + \"Válido até hoje, 23h59\"","\"Últimas horas para aproveitar\": 4 produtos"],
 cta="APROVEITAR DESCONTO",urgencia="Até hoje às 23h59.",
 hero_tipo="Notificação de pedido",hv="e-mail em fundo branco com cara de confirmação de pedido: selo \"Notificação do futuro\", resumo do pedido e o total com desconto",
 est="Hero de notificação de pedido → resumo simulado → botão e validade → 4 produtos → garantias",
 ideia="O melhor fechamento de semana da carteira, no fechamento de uma semana.",
 historia="Ato 2, capítulo 4.",
 ref=["notif"],conexao="Fechamento de semana de oferta, como em 28/08. Melhor fora de pico da carteira: 1,67 em 39 lojas, 3,61% de clique. Copy real da versão Brasil.",
 booster=dict(quando="17h (delay de 7h)",para="nonOpeners",assunto="⏳ A Pré-Black termina hoje às 23h59"),canais="Push 17h: \"Pré-Black termina hoje.\""),
dict(data="2026-10-24",hora="10:00",janela="Semana Pré-Black (19 a 24/10)",contexto="Semana Pré-Black",papel="Reabertura de um dia",
 nome="Eu decidi reabrir a Pré-Black por mais um dia",publico={"A":"E30 + clicou na semana e não comprou","B":"E30 + clicou na semana e não comprou","C":"Clicou na semana e não comprou"},
 oferta="PREBLACK15 reaberto até sábado às 23h59.",
 assunto="Eu decidi reabrir a Pré-Black por mais um dia",assunto_en="I decided to reopen Pre-Black Friday for one more day",
 pre="Só até hoje às 23h59.",
 hero="Texto da [Gerente]",sub="",
 blocos=["\"Oi, [nome]! Aqui é a [Gerente], falando direto com você.\"",
  "\"Ontem, às 23h59, a Pré-Black encerrou oficialmente. Mas quando olhei os números do fim do dia, aconteceu algo que eu não esperava: muita gente clicando no e-mail com o cupom já fora do ar.\"",
  "\"Então parei uns 15 minutos para pensar e tomei uma decisão: vou reabrir tudo por mais um tempo. Só até 23h59 de hoje, a oferta continua a mesma: até 30% + 15% extra com o cupom PREBLACK15.\"",
  "\"APROVEITAR A REABERTURA >>>\"",
  "\"Depois das 23h59 de hoje, o mesmo produto volta ao preço cheio. E aí pode ser tarde... e desta vez é sério.\" \"APROVEITAR AGORA >>>\""],
 cta="APROVEITAR A REABERTURA >>>",urgencia="Só hoje.",
 hero_tipo="Texto puro",hv="e-mail só de texto assinado pela gerente",est="Texto → oferta em negrito → link → reforço do prazo → link",
 ideia="A reabertura real de 25/07, palavra por palavra, agora assinada pela [Gerente]. Ela decide sozinha, e isso vai ter consequência.",
 historia="Ato 2, capítulo 5. A [Gerente] reabre a promoção por conta própria (o [Fundador] vai citar isso em 02/11).",
 ref=["reabertura"],conexao="Reabertura real de 25/07: 1,15 na amostra ampla (17 de 28), 8 pedidos na Blue Wolf. Vai só para quem mostrou interesse na semana.",
 booster=None),
# ================= ATO 3: O HALLOWEEN DA GERENTE (2025) =================
dict(data="2026-10-29",hora="10:00",janela="Halloween da [Gerente] (29/10 a 01/11)",contexto="Halloween (Dia das Bruxas no Brasil): quanto mais você leva, maior o desconto",papel="Soft sell (e-mail 01 de 2025)",
 nome="Promoção progressiva de Halloween",publico=E90,
 oferta="Progressivo: 1 produto 10% · 2 produtos 15% · 3 ou mais 20% (HALLOWEEN10, HALLOWEEN15, HALLOWEEN20), até sábado, 31/10, às 23h59.",
 assunto="Quanto mais você leva, maior o desconto 🎃",assunto_en="The more you buy, the bigger the discount 🎃",
 pre="10%, 15% ou 20%. Você escolhe no carrinho, até sábado.",
 hero="Quanto mais você leva, maior o desconto",sub="De hoje até sábado: 10%, 15% ou 20%, dependendo de quantos itens entram no carrinho.",
 blocos=["Hero com gancho de Halloween e a mecânica + selo \"até 20%\" (estrutura do e-mail 01 de 2025)",
  "Corpo em 3 parágrafos curtos: por que a promoção existe (\"a [Gerente] quis fechar outubro com uma brincadeira\"), a mecânica clara, o prazo",
  "Mini proposta de valor com 3 ícones: envio rápido · troca fácil · pagamento seguro",
  "Grade 2x2 com preço \"de\" e \"por\"",
  "Reforço da mecânica no fim, com as três caixas 10 · 15 · 20"],
 cta="MONTAR MEU KIT",urgencia="Até sábado às 23h59.",
 hero_tipo="Hero de oferta com mecânica",hv="hero com tema de Halloween discreto e as três caixas de desconto 10%, 15% e 20% crescendo da esquerda para a direita",
 est="Hero com gancho e mecânica → selo até 20% → 3 parágrafos → 3 ícones de valor → grade 2x2 de/por → reforço da mecânica → garantias",
 ideia="O Halloween de 2025, igual: é a abertura da sequência que termina no 11.11.",
 historia="Ato 3, capítulo 1. A [Gerente] fecha outubro com uma promoção dela.",
 ref=["kit25"],conexao="É o e-mail 01 da sequência de 2025, com resultado na carteira. O progressivo por quantidade é a mesma mecânica do kit da Black Week de 2025 (12/18/22). Sobe o ticket sem aumentar o desconto de cada peça.",
 booster=None),
dict(data="2026-10-31",hora="10:00",janela="Halloween da [Gerente] (29/10 a 01/11)",contexto="Halloween termina hoje, e outubro também",papel="Catálogo (e-mail 02 de 2025) e fechamento do mês",
 nome="Halloween e outubro terminam hoje",publico=E90,
 oferta="Mesmo progressivo (10/15/20), até 23h59. Frete grátis só se a loja oferecer.",
 assunto="Ignore este e-mail depois das 23h59",assunto_en="Ignore this email after 11:59 PM",
 pre="O progressivo de Halloween acaba à meia-noite.",
 hero="Hoje ainda é outubro. Amanhã não.",sub="A promoção progressiva de Halloween e os preços de outubro saem do ar à meia-noite.",
 blocos=["Banner com a copy batendo na oferta: \"10% · 15% · 20%. Só até 23h59.\"",
  "\"Outubro fechando · 31\": regra curta (sem cupom novo, progressivo no carrinho, até 23h59)",
  "Catálogo de 8 produtos (estrutura do e-mail 02 de 2025)",
  "\"Hoje ainda é outubro. Amanhã não.\" + botão"],
 cta="VER TUDO ANTES DA VIRADA",urgencia="Até 23h59.",
 hero_tipo="Calendário",hv="folha de calendário com o dia 31 de outubro e as três caixas de desconto",
 est="Banner de oferta com prazo → regra curta → catálogo de 8 produtos → frase de virada → garantias",
 ideia="Junta o catálogo de Halloween de 2025 com o fechamento de mês que teve 2,91% de clique.",
 historia="Ato 3, capítulo 2.",
 ref=["catalogo","kit25"],conexao="Catálogo fecha mês: 2,91% de clique e 1,13 nas 9 lojas, com copy real da versão Brasil (\"Hoje ainda é agosto. Amanhã não.\"). O catálogo de 8 produtos é o e-mail 02 de 2025.",
 booster=None),
]
