# Referencias reais da Convertfy: imagem, nome da campanha, copy transcrita e dado
R = {
"convite77": dict(img="jul_0701.jpg", nome="[01/07] - [10:00] - [TODOS OS LEADS] - [1 - ANTECIPAÇÃO 7.7] - [INGLÊS]",
  copy="Selo \"You're officially invited\" · 7.7 Summer Sale · 7AM · 11AM · 18PM · botão \"Confirm your spot\" · \"Something has been quietly taking shape at Wolf Blue Store\" · datas dos próximos e-mails (03/07, 06/07, 07/07) · barra \"Your invitation status: sent, read, confirmed\". Sem oferta e sem produto.",
  dado="Blue Wolf: 41,0% de abertura, 2,46% de clique, 8 pedidos, US$ 46,8 por mil envios. 9 lojas: índice 1,55. Assunto \"[Nome], you have received an invitation ✉️\": abertura 1,27, receita 1,34, 4 de 5 lojas acima da média."),
"agenda77": dict(img="jul_0703.jpg", nome="[03/07] - [10:00] - [TODOS OS LEADS] - [2 - ANTECIPAÇÃO 7.7] - [INGLÊS]",
  copy="\"Invitation update\" · 7.7 Summer Sale · 7AM 11AM 18PM · \"3 windows. 3 moments. Those who know, arrive early.\" · botão \"I want to get ready\" · \"On Wednesday we sent you an invitation. Today, as promised, here's the full schedule\" · \"The 3 moments of 7.7\": 7AM acesso antecipado, 11AM destaque, 18PM chamada final · FAQ com 4 perguntas (preciso me inscrever, vale no site, e se eu perder as 7h, vai ser prorrogado) · barra de status em \"confirmed\".",
  dado="Blue Wolf: 44,3% de abertura (a maior do trimestre), 14 pedidos, US$ 84,1 por mil, sem cupom. Vendeu mais que o 07h do próprio dia. Assunto \"[Nome], have you seen what is coming? 👀\": abertura 1,21, receita 1,77, 5 de 5 lojas."),
"vespera88": dict(img="ago_0807.jpg", nome="[07/08] - [10:00] - [TODOS OS LEADS] - [3 - ESQUENTA 8.8] - [INGLÊS]",
  copy="\"Tomorrow is 8.8. Are you ready?\" · \"Ready for tomorrow?\" com quatro ações · produtos que já estão em oferta no site · bilhete \"First come, first served\". Pré-cabeçalho: \"7 AM, 11 AM, 6 PM. The earlier you arrive, the better the selection.\"",
  dado="Blue Wolf: 10 pedidos, US$ 45,9 por mil, o melhor dos três esquentas do 8.8. Na Emyerre a véspera foi o melhor e-mail do 9.9. 9 lojas: 0,72."),
"cal99": dict(img="set_0905.jpg", nome="[05/09] - [10:00] - [TODOS OS LEADS] - [2 - ESQUENTA 9.9] - [INGLÊS]",
  copy="Folha de calendário com o dia 9 circulado · \"Three time slots in one day\" · \"The biggest deal that Blue Wolf has ever launched\" · botão \"Secure my access\" · 4 produtos do warm-up.",
  dado="Blue Wolf: 12 pedidos, o melhor dos quatro esquentas do 9.9, mesmo indo para 22 mil contatos."),
"anuncio25": dict(img="2025_0511.jpg", nome="Blue Wolf, 05/11/2025, aquecimento do 11.11, e-mail 1",
  copy="\"Blue Wolf with up to 60% off\" · \"The time is coming! 11.11, 24 hours with exclusive discounts\" · \"You are in VIP LIST with guaranteed early access\" · \"Why you can't miss: upgrade your wardrobe, real economy, stock up for the whole year, single chance in 2025\" · \"Only 7 days left until the Black Friday Pre-Sale\" · \"How to guarantee your discount on 11.11\": Step 1 (05/11 a 10/11) escolha e ponha no carrinho, Step 2 (11/11 00:01) alarme às 23h50 do dia 10, Step 3 finalize rápido.",
  dado="11.11 de 2025: sequência de 8 e-mails de aquecimento que antecedeu o maior mês da carteira (seção 15 e 16 do estudo). Sem número isolado por e-mail."),
"prova25": dict(img="2025_0711.jpg", nome="Blue Wolf, 07/11/2025, aquecimento do 11.11, e-mail 3",
  copy="\"You've secured access to Black Friday, November 11th at 7AM\" · \"VIP LIST\" · \"Hey, this is the Wolf Blue Store team. We just finished checking our Black Friday stock...\" · \"These are the 6 products that always SELL OUT\" · \"Why am I showing you this? So you can access exclusive discounts and be ready\" · \"On November 11 at 7AM you will receive an email with: direct link, exclusive discounts, priority shipping\" · \"Mark your calendar 11.11 - 7H\".",
  dado="Tangibilização e prova do aquecimento de 2025. Combina com a agenda do 7.7 (índice de receita 1,77)."),
"bonus25": dict(img="2025_0811.jpg", nome="Blue Wolf, 08/11/2025, aquecimento do 11.11, e-mail 4",
  copy="\"Black Friday Advance, Day only 11.11\" · \"It's coming: BIG DAY\" · \"We are four days away from 11/11 and 60% of people have asked me...\" · \"Most people do this\" contra \"Method correct\" · \"On 11.11 you will be able to: test any product, exclusive discounts, priority shipping\" · \"BONUS progressive discount 10% · 15% · 20%\" · \"Exclusive bonus only for the first 100 people\".",
  dado="Bônus revelado antes do dia, exclusivo para os 100 primeiros. Mesma lógica dos \"primeiros 100\" do 8.8 e do Turbo Monday."),
"check25": dict(img="2025_1011.jpg", nome="Blue Wolf, 10/11/2025, véspera do 11.11",
  copy="\"Black Friday Advance, 24 hours of exclusive offers 11.11 at 7AM\" · \"I want to prepare\" · \"7:00 A.M. official opening\" com os horários 10:59, 5:59 PM, 9:59 PM · \"Favorites that sell out fast at 11.11\" · \"11.11 Checklist: set the alarm for 6:55 AM, confirm your delivery address, decide now your product, add your card on the website\" · \"See you tomorrow at 7 o'clock sharp\".",
  dado="Véspera com checklist, o formato de véspera que vendeu no 8.8 (10 pedidos) e na Emyerre no 9.9."),
"early25": dict(img="2025_1111a.jpg", nome="Blue Wolf e Dr. Melaxin, 11/11/2025, disparo 1",
  copy="\"11/11/2025 only until 11:59 PM today\" · \"Black Friday Early Access\" · \"até 50% OFF + 22% extra\" · cupom 24HOURS · \"24 hours, 24 products, additional 22% off\" · \"The big day is here! We have carefully selected 24 best-selling products...\" · \"It's simple\" (4 passos) · \"Why can't you leave it for later?\" (5 motivos: esgota, 50% + 22%, recebe antes, frete expresso, exclusivo do 11.11).",
  dado="Abertura do 11.11 de 2025, primeiro disparo do dia. Oferta dupla na primeira tela, como a Mid-Year Black de 2026 (até 37% + 15%), que fez o recorde de pedidos do trimestre."),
"vip25": dict(img="2025_1111b.jpg", nome="Blue Wolf e Dr. Melaxin, 11/11/2025, disparo 2",
  copy="\"Early access open to only [N] VIPs\" · \"22% OFF\" · cupom BLACKVIP · \"Release discount\" · \"It is 1:27 PM on November 11... writing an email only to a select few members of the VIP club\" · \"The truth about the VIP CLUB\" · \"Your email: filter 1 premium base, filter 2 engagement, filter 3 VIP profile\".",
  dado="Segundo disparo do 11.11 de 2025. Os números do e-mail precisam ser os reais da loja (achado do estudo, seção 15)."),
"cem25": dict(img="2025_1111d.jpg", nome="Blue Wolf e Dr. Melaxin, 11/11/2025, disparo 4",
  copy="\"Black November Advance, 22% off sitewide\" · \"Only in the next 100 orders\" · cupom BLACKVIP · \"It ended so quickly that we decided to unlock it for another 100 people. But take advantage and close your first cart now.\"",
  dado="Quarto disparo do 11.11 de 2025, escassez por quantidade real."),
"bwconvite25": dict(img="2025_1711.jpg", nome="Blue Wolf, 17/11/2025, anúncio da Black Week",
  copy="\"Black Week, 5 days of deals, November 24 to 28\" · \"New offers every day at 11AM\" · \"Get my VIP access\" · \"Forget everything you know about Black Friday. This year it's not just one day. It's 5 full days of aggressive deals.\" · \"Here's how it works\": um dia por linha · \"Bonus: express shipping for the first 50 customers each day\" · \"Each day = new products\" · \"You are on the VIP list\" · \"Mark your calendar\" · \"Remember this number: 1,247\".",
  dado="Abertura da antecipação da Black Week de 2025. Estrutura de convite com agenda, o mesmo desenho do 7.7 (a melhor antecipação de 2026)."),
"n1247": dict(img="2025_1911.jpg", nome="Blue Wolf, 19/11/2025, prova da Black Week",
  copy="\"The number of frustration: 1,247\" · \"Last year, 1,247 people clicked add to cart and saw: out of stock\" · \"Don't be one of them\" · \"How we got to these 6 products\" · \"These are the 6 products that always sell out\" · \"Do this now: go to each product, click add to wishlist\" · \"Mark your calendar\" · \"Check your payment info: log in, credit card, shipping address, test run\".",
  dado="Prova e tarefa antes do pico. O número precisa ser o real da loja."),
"lastvip25": dict(img="2025_2311.jpg", nome="Blue Wolf, 23/11/2025, última chance da lista VIP",
  copy="\"Last chance: VIP LIST ends today in 24h\" · \"Black Week starts tomorrow and it will be bigger than anything we've ever done. But there's a problem...\" · \"Whoever is registered on the VIP list gets: early access, exclusive discounts, products released first\" · \"Whoever doesn't register by 11:59 PM today: regular queue, what's left, miss out on extra discounts\" · \"How to guarantee your VIP spot\" (2 passos) · \"Exclusive release for VIPs\".",
  dado="Fechamento da lista VIP na véspera. Transforma a véspera em prazo, não em lembrete."),
"bw24_25": dict(img="2025_2411.jpg", nome="Blue Wolf, 24/11/2025, Black Week dia 1",
  copy="\"Black Week has arrived\" · \"24 hours | 24 products\" · \"20% OFF\" · cupom BLACKWEEK · \"The big day, it's here! 24 hours, 24 products, additional 20% off\" · \"It's simple\" (4 passos) · \"Why can't you leave it for later?\" · \"Black Week continues on other days. But the 20% coupon on the 24 favorites is exclusive to Monday.\"",
  dado="Primeiro dia da Black Week de 2025: oferta do dia com prazo de 24 horas."),
"bwcol25": dict(img="2025_2511.jpg", nome="Blue Wolf, 25/11/2025, Black Week dia 2",
  copy="\"Black Week, up to 60% OFF + 20% extra\" · cupom BLACKWEEK · \"Shop by collection\" (4 coleções com foto) · \"Shop by price\": $99, $199, $299, $399 · \"See more offers\".",
  dado="Segundo dia de 2025: navegação por coleção e por faixa de preço, sem texto longo."),
"kit25": dict(img="2025_2611.jpg", nome="Blue Wolf, 26/11/2025, Black Week dia 3",
  copy="\"Build your premium leather collection today. The more pieces you add, the more you save.\" · \"How much more you buy, the bigger the discount\": 12% BLACK12, 18% BLACK18, 22% BLACK22 · \"Get an exclusive gift: the first 100 orders get a surprise gift\" · \"Savings that grow with your cart\".",
  dado="Progressivo por quantidade com brinde para os 100 primeiros. Mesma mecânica do Halloween e do 12/11 de 2025."),
"bf1_25": dict(img="2025_2811a.jpg", nome="Blue Wolf, 28/11/2025, Black Friday disparo 1",
  copy="\"The day has arrived: Black Friday\" · \"Up to 50% OFF\" · cupom BLACK · \"Last chance of the year: extra 23% off\" · \"It's simple\" · \"Why you shouldn't wait\": o cupom expira à meia-noite, 50% + 23%, compra hoje e recebe rápido, frete prioritário, produtos exclusivos · \"At midnight this page disappears. Literally.\"",
  dado="Dia principal de 2025: a maior oferta do ano, com prazo de meia-noite."),
"bf2_25": dict(img="2025_2811b.jpg", nome="Blue Wolf, 28/11/2025, Black Friday disparo 2",
  copy="\"Black Friday\" · \"Surprise gift with order at your door\" · \"23% OFF storewide\" · cupom BLACK · \"Your Black Friday gift has arrived... but don't worry, it's not a purchase! It's something even better\" · \"Exclusive Black Friday via e-mail\".",
  dado="Segundo disparo da BF de 2025: brinde surpresa como motivo novo no mesmo dia."),
"cm25": dict(img="2025_0112.jpg", nome="Blue Wolf, 01/12/2025, Cyber Monday",
  copy="\"Cyber Monday VIP exclusive\" · \"Last chance for get 23% OFF\" · cupom VIP23 · \"Missed Black Friday? Relax, there's still time. We extended the discount for Cyber Monday.\"",
  dado="Em 2025 a CM foi extensão do cupom da BF. O dado de 2026 (VIP Week 0,52; Dia do Cliente 47% abaixo) diz que extensão não sustenta um segundo evento. Referência do que não repetir."),
"cupom99": dict(img=None, nome="[09/09] - [07:00] - [TODOS OS LEADS] - [1 - 9.9] - [INGLÊS] (texto)",
  copy="E-mail em texto, com pessoa no remetente. Assunto \"Your coupon has been released ✅\". Cupom 0909 em negrito, prazo até meia-noite, um link. Na Clube Rock, a versão em português (\"Seu cupom foi liberado ✅\") com remetente Henrique foi o disparo de maior índice da loja (07h: 1,78).",
  dado="Blue Wolf: 13 pedidos, US$ 72,3 por mil. 9 lojas: 1,66. 46 lojas: 0,95. Clube Rock, papel \"pico 07h\": índice 1,78, o melhor da loja."),
"relogio99": dict(img="set_0909b.jpg", nome="[09/09] - [11:00] - [TODOS OS LEADS] - [2 - 9.9] - [INGLÊS]",
  copy="Cabeçalho com 7AM, 11AM e 6PM e os dois primeiros marcados · \"9.9 New Season Sale\" · \"New season. New wardrobe.\" · \"19% OFF\" cupom 0909 · \"9.9 New Season Sale is live. From your first coffee until the last light goes out.\" · botão \"I want to shop now\" · relógio e linha do tempo de 07:00 a 00:00 com \"11:00, 19% OFF is live for everyone\".",
  dado="9 lojas: 1,24. 46 lojas: 0,67. Blue Wolf: 2,70% de clique. O mais longo da amostra (4.136 px): cortar pela metade."),
"cem88": dict(img="ago_0808b.jpg", nome="[08/08] - [11:00] - [TODOS OS LEADS] - [2 - 8.8] - [INGLÊS]",
  copy="\"8.8 End of Summer\" · \"The first 100 get their summer favorites with this special deal. Use the coupon 0808 to secure yours\" · \"18% OFF sitewide\" · \"Shop now\" · \"But hurry: this offer expires at 11:59 PM\" · \"Today's top picks\" · \"Still not sure what to get?\"",
  dado="Blue Wolf: 8 pedidos. 46 lojas: 0,46. O limite de 100 só vale se existir no cupom do Shopify."),
"conversa88": dict(img="ago_0808c.jpg", nome="[08/08] - [18:00] - [TODOS OS LEADS] - [3 - 8.8] - [INGLÊS]",
  copy="\"8.8 End of Summer\" · conversa de celular: Thomas: \"Check the site, 18% OFF on everything today with coupon 0808\" · \"Already got mine. Half the stuff I had my eye on is already sold out\" · James: \"Really? Is there still good stuff?\" · Thomas: \"They do! But it's going fast... and only until midnight. Don't leave it for later\" · James: \"I'm going now!!\" · foto do modelo com o produto · cupom · \"There's still time to grab these\" · \"Now or never\" com o cupom repetido.",
  dado="A melhor campanha do trimestre na Blue Wolf: 18 pedidos, US$ 107,5 por mil, 42,2% de abertura. 46 lojas: 1,48 (25 de 33). Assunto \"🚨 Your status has just changed\": abertura 1,34, receita 2,13, 5 de 5 lojas."),
"jornal99": dict(img="set_0909c.jpg", nome="[09/09] - [18:00] - [TODOS OS LEADS] - [3 - 9.9] - [INGLÊS]",
  copy="\"Breaking news\" · \"Wednesday, September 9, 2026\" · \"6 hours left\" · \"9.9 New Season Sale\" · \"The campaign ends today at 11:59 PM. Get 19% off sitewide with coupon 0909 at checkout.\" · cupom 0909 · foto da embalagem · \"Headline highlights\" com 4 produtos.",
  dado="Blue Wolf: 15 pedidos, 3,56% de clique. 9 lojas: 1,90. 46 lojas: 1,04. Assunto \"🚨 Your status has just changed\" no 9.9: receita 1,71, 4 de 5."),
"lastcall77": dict(img="jul_0707c.jpg", nome="[07/07] - [18:00] - [TODOS OS LEADS] - [3 - 7.7] - [INGLÊS]",
  copy="\"Last call\" · \"7.7 Summer Sale\" · \"17% OFF\" · \"Use code 0707\" · \"Shop now\" · \"Expires tonight 11:59 PM\" · \"The morning sun is starting to fade. A few hours left. Midnight...\" · 4 produtos · linha do tempo \"The sun is clocking out\" com 7AM, 11AM, 18PM e 12AM. Assunto \"🚨 [FINAL CALL] Expires at 11:59 PM\".",
  dado="Blue Wolf: 14 pedidos, US$ 105,3 por mil, 3,06% de clique, a segunda melhor do trimestre. 46 lojas: 1,22. 9 lojas: 1,46."),
"ressaca99": dict(img="set_0911.jpg", nome="[11/09] - [10:00] - [TODOS OS LEADS] - [RESSACA 9.9] - [INGLÊS]",
  copy="Faixa \"Active deals, no coupon required\" · caixa \"Notice: September 11, 2026\" · \"Due to high demand during 9.9 New Season Sale, stock levels for several products are much lower than usual. Promotional prices remain active on the site, but once current stock runs out, we will not be able to keep these offers.\" · \"See remaining stock\" · \"Get the last items\" com 4 produtos. Assunto \"We regret to inform you that...\".",
  dado="Blue Wolf: 14 pedidos, US$ 77,7 por mil, a melhor de setembro, descadastro 0,29%. Rendeu o dobro da ressaca do 8.8 (\"Missed our 8.8 sale?\")."),
"favoritos77": dict(img="jul_0715.jpg", nome="[15/07] - [10:00] - [TODOS OS LEADS] - [FAVORITOS DO 7.7] - [INGLÊS]",
  copy="\"The bestsellers\" · \"7.7\" · \"Limited units left\" · \"The pieces everyone wanted during the summer sale are still here. Not for long.\" · \"Shop the bestsellers\" · foto grande do produto · \"The 7.7 champions\" com 4 produtos. Assunto \"[Nome], your 7.7 favorites are waiting for you\".",
  dado="Blue Wolf: 14 pedidos, US$ 71,3 por mil, 3,19% de clique. 46 lojas: 1,12. Oito dias depois do evento, com os preços mantidos só nos mais vendidos."),
"revele": dict(img="jul_0720.jpg", nome="[20/07] - [10:00] - [TODOS OS LEADS] - [REVELE SEU DESCONTO] - [INGLÊS]",
  copy="Papel rasgado revelando \"+15% OFF\" sobre \"until 37% OFF\" · cupom EXTRA e validade logo abaixo · botão \"Reveal now\" · 4 produtos. Assunto \"(1) hidden discount for [nome] inside this email 🤫\".",
  dado="Blue Wolf: 18 pedidos, o recorde do trimestre (abertura da Mid-Year Black Sale). 9 lojas: 1,22. Assunto: abertura 1,04, receita 1,50, 4 de 5. Na amostra ampla é disperso: forte em 13 de 29 lojas."),
"jornal22": dict(img="jul_0722.jpg", nome="[22/07] - [10:00] - [TODOS OS LEADS] - [JORNAL] - [INGLÊS]",
  copy="\"Breaking News\" · \"Wednesday, July 22, 2026\" · \"48H until the end of the mid-year Black Sale\" · \"The campaign ends on Friday (07/24) at 11:59 PM. Up to 37% OFF on the site + 15% OFF with the EXTRA coupon at checkout.\" · cupom EXTRA · foto da embalagem · \"The headline highlights\". Assunto \"[Nome], the news you did not want to hear has arrived...\".",
  dado="Blue Wolf: 15 pedidos, US$ 71,9 por mil. 9 lojas: 1,62. 46 lojas: 1,10. Assunto: abertura 1,06, receita 1,59, 4 de 5."),
"ligacao": dict(img="jul_0724.jpg", nome="[24/07] - [10:00] - [TODOS OS LEADS] - [LIGAÇÃO] - [INGLÊS]",
  copy="\"Your last chance is calling you...\" · celular com \"Incoming call\" · \"Up to 37% OFF + 15% extra\" · cupom EXTRA · \"Mid-Year Black Sale\" · botões recusar e atender · CTA \"Accept\" · \"The products on the line\" com 4 produtos. Assunto \"[Nome], you have an incoming call\".",
  dado="Blue Wolf: 11 pedidos no terceiro envio da mesma oferta na semana. 46 lojas: 1,17 (15 de 28). Revele, jornal e ligação somaram 44 pedidos e US$ 2.944."),
"reabertura": dict(img="reabertura_2507.jpg", nome="[25/07] - [10:00] - [TODOS OS LEADS] - [REABERTURA] - [INGLÊS]",
  copy="Texto puro assinado pelo fundador. \"Hello, [nome]! Michael here, founder of Blue Wolf, speaking directly to you. Yesterday, at 11:59 PM, the Mid Year Sale officially closed. But when I looked at the end-of-day numbers, something happened that I did not expect: there were a lot of people clicking on the email with the coupon already offline. So I stopped to think for about 15 minutes and made a decision: I am reopening everything for a little longer. Only until 11:59 PM today, the offer stays the same: UP TO 37% OFF + 15% OFF with the coupon EXTRA at checkout. TAKE ADVANTAGE OF THE REOPENING >>> ... After 11:59 PM today, the same product goes back to full price. And by then it may be too late... and this time I mean it. TAKE ADVANTAGE NOW >>> Warm regards, Michael, Founder of Blue Wolf\". Assunto \"I decided to reopen everything for one more day.\"",
  dado="Blue Wolf: 8 pedidos, US$ 50,1 por mil. 46 lojas: 1,15 (17 de 28). 9 lojas: 1,11."),
"onoff": dict(img="ago_0824.jpg", nome="[24/08] - [10:00] - [TODOS OS LEADS] - [1 - SEMANA 15%, ON & OFF] - [INGLÊS]",
  copy="Interruptor \"Full price: OFF\" e \"15% OFF: ON\" · \"Some weeks call for a better deal. This is one of them.\" · cupom WEEK15 · \"Valid until Friday 11:59 PM\" · botão \"Activate my 15%\" · \"The easy picks\" com 4 produtos · interruptor repetido no fim. Assunto \"I've activated a discount for you\".",
  dado="Blue Wolf: 8 pedidos, 2,89% de clique, o melhor da semana de 15%. 9 lojas: 0,99 (5 de 9)."),
"notif": dict(img="ago_0828.jpg", nome="[28/08] - [10:00] - [TODOS OS LEADS] - [3 - SEMANA 15%, NOTIFICAÇÃO DO FUTURO] - [INGLÊS]",
  copy="Fundo branco · \"Notification from the future\" · \"Your order will be on its way ✓\" · \"We came from the future (not that far) to let you know, you didn't let this one slip. It's the last day of your 15% OFF coupon and you didn't leave it for the weekend.\" · \"Your future self says thanks\" · resumo de pedido simulado com o cupom WEEK15 aplicado · \"Get the discount\" · \"Valid until Friday 11:59 PM\" · \"Last hours to take advantage\" com 4 produtos. Assunto \"[Nome], you still need to confirm your order...\".",
  dado="É o FECHAMENTO de uma semana de oferta. Blue Wolf: 3,61% de clique, o maior do trimestre. 46 lojas: 1,67 (24 de 39), o melhor fora de pico da carteira. Assunto: abertura 1,14, receita 1,52."),
"catalogo": dict(img="ago_0831.jpg", nome="[31/08] - [10:00] - [TODOS OS LEADS] - [CATÁLOGO FECHA MÊS] - [INGLÊS]",
  copy="\"August ends today\" · \"The prices on essentials that ran all month long end at midnight. No code needed, everything is already marked down on the site until 11:59 PM.\" · \"Get it while you can\" · \"August. Tomorrow isn't.\" com 4 produtos. Assunto \"Ignore this email after 11:59 PM\".",
  dado="Blue Wolf: 8 pedidos, 2,91% de clique, prazo sem desconto novo. 9 lojas: 1,13. 46 lojas: 0,79."),
"turbo": dict(img="ago_0817.jpg", nome="[17/08] - [10:00] - [TODOS OS LEADS] - [SEGUNDA TURBO] - [INGLÊS]",
  copy="\"Turbo Monday, only for the first 100\" · símbolos \"$ % ?\" em papel rasgado · \"Only the fastest win: enter the coupon TURBO100 and discover the surprise at checkout\" · \"Discover now\" · 4 produtos. Assunto \"Are you among the first 100?\".",
  dado="Blue Wolf: 6 pedidos com ticket de US$ 158 (o mais alto do mês), US$ 60,4 por mil. 9 lojas: 1,06. 46 lojas: 0,83."),
"figurinha": dict(img=None, nome="[19/06] - [10:00] - [LEADS ENGAJADOS] - [ÁLBUM DE FIGURINHA] - [INGLÊS]",
  copy="Gamificada: o código revela o desconto. Assunto \"You've unlocked the golden sticker\". Enviado só para leads engajados.",
  dado="9 lojas: 1,80. 46 lojas: 1,35. Blue Wolf: 6 pedidos."),
"finalcopa": dict(img="jul_0718.jpg", nome="[18/07] - [10:00] - [TODOS OS LEADS] - [FINAL DA COPA] - [INGLÊS]",
  copy="\"The final is tomorrow. Your victory is today.\" · \"The world pauses tomorrow for the final. We're rewarding you today.\" · \"Claim my trophy now\" · \"The champion's offers\" com 4 produtos · no fim, o anúncio da Mid-Year Sale para segunda 20/07 às 10h. Assunto \"[Nome], I've set something aside just for our special customers 🏆\".",
  dado="Blue Wolf: 13 pedidos, US$ 55,5 por mil. Assunto: abertura 1,07, receita 1,35. Fez a ponte para a venda da semana seguinte."),
}

R.update({
"esq88a": dict(img="ago_0803.jpg", nome="[03/08] - [10:00] - [TODOS OS LEADS] - [1 - ESQUENTA 8.8] - [INGLÊS]", fig=("agosto","campanha - 03/08"),
  copy="Esquenta com ofertas ativas no site durante a antecipação e os três horários do dia.", dado="Blue Wolf: 1 pedido, o pior do trimestre. Falou do evento, não da pessoa. Serve de referência do que ajustar, não do tom."),
"esq88b": dict(img="ago_0805.jpg", nome="[05/08] - [10:00] - [TODOS OS LEADS] - [2 - ESQUENTA 8.8] - [INGLÊS]", fig=("agosto","campanha - 05/08"),
  copy="Contagem regressiva (\"faltam 3 dias\"), \"como vai funcionar o 8.8\" com os três horários e as ofertas de esquenta ativas.", dado="Blue Wolf: 6 pedidos. 9 lojas: 0,78, o melhor esquenta do 8.8 em receita na amostra."),
"esq99a": dict(img="set_0907.jpg", nome="[07/09] - [10:00] - [TODOS OS LEADS] - [3 - ESQUENTA 9.9] - [INGLÊS]", fig=("setembro","campanha - 07/09"),
  copy="\"Às 7h é abertura exclusiva para quem faz parte da nossa lista. E se você abriu este e-mail e está lendo, automaticamente você faz parte.\" \"Quatro horas de vantagem antes do site abrir para o público.\" Na versão Brasil, o e-mail do dia 07/09 ainda trouxe o cupom LIBERDADE (Independência).", dado="Blue Wolf: 3 pedidos no segmento de 22 mil (o problema foi a lista ampliada e a promessa repetida, não o mecanismo da abertura exclusiva)."),
"esq99b": dict(img="set_0908.jpg", nome="[08/09] - [10:00] - [TODOS OS LEADS] - [4 - ESQUENTA 9.9] - [INGLÊS]", fig=("setembro","campanha - 08/09"),
  copy="\"Amanhã é o dia\": \"o que vai fazer diferença não é a velocidade, é chegar sabendo o que você quer\", FAQ com 4 perguntas e o bilhete \"hoje 08/09, amanhã 09/09\".", dado="Blue Wolf: 5 pedidos. Na Emyerre foi o melhor e-mail do 9.9."),
"ressaca88": dict(img="ago_0811.jpg", nome="[11/08] - [10:00] - [TODOS OS LEADS] - [RESSACA 8.8] - [INGLÊS]", fig=("agosto","campanha - 11/11"),
  copy="\"Ainda dá tempo\": notificação da loja com \"os itens do 8.8 continuam no site, mas com poucas unidades\" e \"os mais escolhidos do 8.8\".", dado="Blue Wolf: 8 pedidos. Abre bem e clica pouco; a do 9.9, com aviso de estoque, rendeu o dobro."),
"pourri": dict(img="pourri_halloween.jpg", nome="Inspiração externa: Pourri, Halloween (\"Trick or Treat Mystery offer\")",
  copy="\"Don't miss this!\" · três caixas \"! ? %\" · \"Your Trick or Treat Mystery offer expires TODAY. Unlid your cauldron of curiosities before it's gone for good.\" · \"Reveal my offer\".", dado="Sem dado da carteira. Mesma mecânica do nosso Turbo (\"$ % ?\", valor revelado no checkout)."),
"wc": dict(img=None, nome="Inspiração externa: calendário BFCM 2025 de uma marca americana (lista de campanhas enviada)",
  copy="\"(TB) From [fundador]: Why We're Doing EA\" (14/11, 59% de abertura, US$ 11,8 mil) · \"(TB) Forgot Someone? We've Got You\" (18/12, US$ 19,0 mil) · \"(TB) Last-Minute Gifting, Solved\" (22/12, US$ 18,2 mil) · \"Gifts They'll Actually Wear\" (05/12, US$ 13,0 mil) · \"24-Hour Free Priority Shipping\" + \"Priority Ends at Midnight\" (12/12, US$ 9,7 mil + 14,6 mil).", dado="(TB) = texto puro. Os e-mails de texto do fundador e de última hora foram os de maior receita de dezembro nessa lista."),
})
FIGMAP={"vespera88":("agosto","campanha - 07/08"),"cal99":("setembro","campanha - 05/09"),"cem88":("agosto","campanha - 08/08 #2"),"conversa88":("agosto","campanha - 08/08 #3"),
 "relogio99":("setembro","campanha - 09/09 #2"),"jornal99":("setembro","campanha - 09/09 #3"),"ressaca99":("setembro","campanha - 11/09"),"onoff":("agosto","campanha - 24/08"),
 "notif":("agosto","Campanha - 28/08"),"catalogo":("agosto","campanha - 31/08"),"turbo":("agosto","campanha - 17/08"),"sexta":("agosto","campaign - 07/31")}
for k,v in FIGMAP.items():
    if k in R: R[k]["fig"]=v

WCN="Sem medição (cartão da Well Copy: \"performed high above expectation\", sem número). Entra como inspiração de formato."
R.update({
"credit": dict(img="wc_credit_activated.jpg", nome="Estrutura nova enviada: Well Copy, \"Credit Activated\"",
  copy="Hero com celular na tela de bloqueio e a notificação \"[BRAND] $10 Credit Activated. 1m ago\" · \"$10 · Credit added to your account\" · \"Your credit is live and ready to use. Enter code {{ coupon_code }} at checkout\" · botão \"Use My $10 Credit\" · \"100-Day Returns · Free 3-Day Shipping\" · \"Use it on\" com 3 produtos (Bestseller, Most gifted, New arrival) · \"Shop best sellers\".", dado=WCN),
"xidax": dict(img="xidax_gpu_called.jpg", nome="Estrutura nova enviada: Xidax, \"Your GPU called\"",
  copy="Topo com barra de chamada recebida (\"Mobile GPU\", recusar e atender) · \"YOUR GPU CALLED\" · conversa de iMessage: \"Yo. it's CPU.\" · \"Bad news: your GPU just texted me. It's done.\" · \"I'm scared\" · \"Every new game = more more MORE.\" · \"You lower the settings / You cope / You tell yourself it's fine\" · \"The card's calling me RIGHT NOW\" · \"OH\" · \"BRO IT'S TIME\" · campo de iMessage · botão \"ANSWER THE CALL\" · \"Shop by category\".", dado="Sem dado. Junta dois heroes que já funcionam na carteira: a chamada recebida (Ligação, 1,17) e a conversa (8.8 às 18h, 1,48)."),
"wc_slack": dict(img="wc_leaked_slack.jpg", nome="Well Copy: Leaked Email / Slack Message (OVR)",
  copy="Print de grupo interno vazado: \"Just a heads up. Sprint is moving way faster than expected...\" · \"You heard the co-founder (don't tell him we leaked the group chat)\" · botão.", dado=WCN),
"wc_voice": dict(img="wc_voice_note.jpg", nome="Well Copy: Voice Note From The Founder (HQ Germany)",
  copy="\"HEY, it's Severin from HQ Germany\" · \"I wanted to leave you a quick voice note now that our Early Access Black Friday Sale is officially live...\" · \"22% OFF with the code BFCM2025-VIP\" · player de áudio · \"Listen & shop now\".", dado=WCN),
"wc_reddit": dict(img="wc_reddit.jpg", nome="Well Copy: The Reddit (r/OfficeChairs)",
  copy="Post de fórum com título, texto longo de cliente real e comentários · \"Reviews with context\" · botão da loja.", dado=WCN),
"wc_native": dict(img="wc_native_social.jpg", nome="Well Copy: Native Social Media Reviews (Magic Mind)",
  copy="\"You heard it here first\" · prints reais de comentários e DMs do Instagram · \"Try it 100-day risk-free\".", dado=WCN),
"wc_back": dict(img="wc_back_in_stock.jpg", nome="Well Copy: The \"Back In Stock\" (Smoke Show)",
  copy="\"The wait is over\" · \"Our classic Old Fashioned syrup is back!\" · \"It sold out fast last time, so stock up before it's too late!\" · \"Claim yours now\".", dado=WCN),
"wc_code": dict(img="wc_discount_code.jpg", nome="Well Copy: What's The Discount Code (Benchmark Abrasives)",
  copy="\"Do you want to play a game?\" · \"One of these codes will unlock 10% off\" · 8 códigos em botões · \"You only get one shot\" · \"Test your luck\".", dado=WCN),
"wc_gift": dict(img="wc_mystery_gift.jpg", nome="Well Copy: Free Mystery Gift (Benchmark Abrasives)",
  copy="Caixa preta com \"?\" · \"What's that free gift?!\" · \"We're not saying what it is... but it might just spark your next project\" · \"Shop now & reveal it now\".", dado=WCN),
"wc_lottery": dict(img="wc_order_lottery.jpg", nome="Well Copy: Order Lottery Offer",
  copy="E-mail de texto: \"Your order might be on us 🎉\" · quem comprar até a data concorre ao pedido inteiro de graça · os ganhadores são anunciados depois e reembolsados no Shopify.", dado="Sem medição. O cartão diz que \"quebrou vários recordes de campanha de maior receita\"."),
"wc_first": dict(img="wc_first_x.jpg", nome="Well Copy: First X Customers Sale (Smoke Show)",
  copy="\"Valentine's Flash Sale\" · \"Just for today, the first 100 customers who use the code FIRST100 will unlock something extra sweet\" · \"Try it out\" · \"But don't wait... this little love note self-destructs at midnight\".", dado="Mesma mecânica do nosso \"100 primeiros\" (8.8 às 11h, Segunda turbo)."),
"wc_long": dict(img="wc_long_testimonial.jpg", nome="Well Copy: The Looong Testimonial (The Black Stuff)",
  copy="\"Confessions of a soap addict\" · 5 estrelas · um depoimento longo e real de um cliente, com título entre aspas · botão.", dado=WCN),
"wc_loyalty": dict(img="wc_loyalty.jpg", nome="Well Copy: Loyalty Points Offer (The Pod Company)",
  copy="\"Use your loyalty points before they expire\" · \"Your loyalty points will expire in 2 days! You currently have 509 points, which equals $50.90\" · \"How you earned your points\".", dado="Não é programa de fidelidade real: é desconto em dinheiro com cara de pontos."),
"wc_magic": dict(img="wc_magic_button.jpg", nome="Well Copy: Magic Button In Footer",
  copy="E-mail de texto com um botão \"mágico\" no rodapé, sem explicação. As pessoas clicam por curiosidade.", dado=WCN),
})
R["wc_mystery"]=dict(img="wc_mystery.jpg", nome="Well Copy: Mystery Discount Campaign (Forest Ink)",
  copy="\"Unlock your mystery discount\" · \"Will it be 10%, 15%, or 25% off?\" · \"Use code TREAT at checkout to find out how much you'll save\" · \"Reveal your discount\" · três blocos com \"%\".", dado=WCN)

R.update({
"reviews0729": dict(img="jul_0729.jpg", nome="[29/07] - [10:00] - [TODOS OS LEADS] - [SOCIAL PROOF] - [INGLÊS]", fig=("agosto",["campanha - 29/07","campaign - 07/29"]),
  copy="\"6,747 reviews don't lie...\" · \"Real reviews on the end-of-summer favorites. Straight from those who wear them daily.\" · \"See the gifts\" · \"See what they're saying\" com 3 depoimentos grandes, cada um com foto real, nome, 5 estrelas e botão. Na versão Brasil: \"6.747 avaliações não mentem\".",
  dado="Blue Wolf: 7 pedidos, 26,6% de abertura. Sozinho, depoimento sem oferta rende pouco (lição 10); por isso aqui entra só como bloco de prova dentro de um catálogo com oferta."),
"desejo25": dict(img="2025_0611.jpg", nome="Blue Wolf, 06/11/2025, aquecimento do 11.11, criação de desejo e seleção",
  copy="\"Early access to the Black: 24 hours of exclusive discounts on November 11 at 7 A.M.\" · \"Get ready\" · \"You are in VIP LIST · Free access to the best offers of the year\" · \"Imagine opening your wardrobe and everything just works...\" · 3 personas (\"For you who's tired of buying clothes that don't mix and match\"...) · estoque físico limitado · \"Only 6 days left until the Black Friday Advance\".",
  dado="Parte da sequência de 2025 que antecedeu o maior mês da carteira. Bloco a bloco no estudo (15.3): hook \"Imagine...\", 3 personas por dor, ancoragem de valor, \"Você está na lista. De graça.\", escassez real, pergunta com pedido de resposta, P.S."),
"nosxeles25": dict(img="2025_0911.jpg", nome="Blue Wolf, 09/11/2025, aquecimento do 11.11, Nós x Eles",
  copy="\"Here a Black Friday it's out of the ordinary\" · \"See the difference\" · \"73% from the stores inflate prices 30 days before Black Friday...\" · \"Our differential\": tabela Blue Wolf contra \"Others\" (produto rastreável, transparência total, envio imediato, site confiável) · \"Why you can't miss out on 11.11\".",
  dado="Parte da sequência de 2025. O número \"73%\" não tem fonte: em 2026 a tabela usa só critérios verificáveis da loja."),
"balao25": dict(img="2025_1111c.jpg", nome="Blue Wolf e Dr. Melaxin, 11/11/2025, disparo 3 (surpresa)",
  copy="\"Black Friday Advance\" · \"Pop the balloon and win\" · botão \"Burst\" · \"Use the coupon BLACKVIP and get 22% off sitewide\".",
  dado="Terceiro disparo do 11.11 de 2025 (o \"desconto surpresa\" do planejamento). Em 2026, a surpresa entra dentro da conversa das 18h, o formato de maior índice."),
})
R["sexta"]=dict(img="jul_0731.jpg", nome="[31/07] - [10:00] - [TODOS OS LEADS] - [SEXTA PREMIADA] - [INGLÊS]", fig=("agosto",["campanha - 31/07","campaign - 07/31"]),
  copy="\"Friday Rewards\" · chave dourada · \"End the month on a high note before summer is over\" · cupom SUMMER · \"Apply the coupon at checkout to discover your discount. Valid until Saturday at 11:59 PM\" · \"Use my golden key\" · \"Unlock with the key: apply the code at checkout to reveal the discount on each item\". Na versão Brasil: \"Sexta-feira premiada\", cupom PAI, \"destravar o presente do pai\".",
  dado="Blue Wolf: 9 pedidos, US$ 50,2 por mil (3 vezes a Segunda da sorte, que não tinha cupom nem prazo). 46 lojas: 1,17. 9 lojas: 1,22 (7 de 8).")
